### PR TITLE
mangle exported functions for PyPy

### PR DESCRIPTION
**Pull request by mattip**
Continuation of #3031. This [turned up](https://github.com/pypy/binary-testing/actions/runs/4390086363/jobs/7688256133#step:6:179) in the run of PyPy 3.10 HEAD against PyO3 HEAD. Should I add a new news fragment or is the one from #3031 sufficient?

### CODE REVIEW

**Comment by adamreichold** [comment]
I think the existing news fragment is sufficient. Thanks!

bors r+

**Comment by adamreichold** [comment]
@mattip Could you have a look at the build failure in https://github.com/PyO3/pyo3/actions/runs/4396220835/jobs/7698525481 ? Does this need a version limit?

**Review by davidhewitt — COMMENTED** [review]
Sorry I had a pending review comment, just posted - we can do `#[cfg_attr(all(PyPy, Py_3_10), ...)]`

**Comment by messense** [comment]
bors retry

**Pull request merged**
