### PR TITLE
Remove unrequired encoding header

### PR DESCRIPTION
**Pull request by Alisa-lisa**
This is not required anymore for Python 3.

### CODE REVIEW

**Comment by pganssle** [comment]
This library still supports Python 2 for at least a little while, though, I think.

Also, while not required I don't think it hurts to explicitly declare the encoding of the file even if it's the same as the default.

**Comment by kngwyu** [comment]
Let's leave it until python2 support ends :)

**Comment by konstin** [comment]
Yep, but I think we can keep this open until then.

**Comment by milesgranger** [comment]
I'd just add that while it's the _default_ (utf-8) for Python3, so far as Python3 is concerned, it makes no difference, but IDEs will still make use of this declaration.

**Pull request merged**
