### PR TITLE
Add automated continuous benchmarking

### LINKED ISSUE #1634: Automated continuous benchmarking
https://github.com/marketplace/actions/continuous-benchmark

Tokio has an example workflow: https://github.com/tokio-rs/tokio/blob/master/.github/workflows/bench.yml and tracking benchmark result with GH Pages: https://tokio-rs.github.io/tokio/dev/bench/

I can send a PR if this is desirable.

### PR DESCRIPTION
**Pull request by messense**
Closes #1634

### CODE REVIEW

**Comment by itamarst** [comment]
In order to get consistent results (there's a bunch of noise in VM performance: https://bheisler.github.io/post/benchmarking-in-the-cloud/), might be worth trying https://github.com/bheisler/iai.

**Comment by davidhewitt** [comment]
Thanks for implementing this! Sorry it took me a while to look at this, I have a few questions:
 - Do you think it's possible to do in a single job instead of another matrix? It seems unneccessary to split this up into so many small CI jobs.
 - Is it possible to also add the benchmarks from `pyo3-benchmarks` example?
 - What's the URL to see the graphs? (Let's add this to the guide? 😃)

**Comment by messense** [comment]
> * Do you think it's possible to do in a single job instead of another matrix? It seems unneccessary to split this up into so many small CI jobs.

Done.

> * Is it possible to also add the benchmarks from `pyo3-benchmarks` example?

Will try add that later.

> * What's the URL to see the graphs? (Let's add this to the guide? 😃)

I think it will be https://pyo3.rs/dev/bench/ , it adds a `dev/bench` directory in gh-pages branch.

**Comment by messense** [comment]
> In order to get consistent results (there's a bunch of noise in VM performance: https://bheisler.github.io/post/benchmarking-in-the-cloud/), might be worth trying https://github.com/bheisler/iai.

iai is a relatively new project. I don't think `github-action-benchmark` supports its output format yet.

**Comment by davidhewitt** [comment]
Great! Let's merge this and start getting a feel for what this tells us.

**Review by davidhewitt — APPROVED** [review]

**Pull request merged**
