### PR TITLE
Add regression test for TypeError after returning NotImplemented.

### PR DESCRIPTION
**Pull request by mvaled**
This PR adds a regression test for issue #1185.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thank you for finding this!
Looks the bug is around https://github.com/PyO3/pyo3/blob/a0960f891801c0534856cb90fa90451828579470/src/class/macros.rs#L128.
Here we use `extract_or_not_implemented!` even after the fallback call, but we should raise type error instead.

Are you willing to fix this yourself on this branch?
Or I can send a PR on this.

**Comment by mvaled** [comment]
@kngwyu Now that you have pinpointed the place where it happens I could try to fix it.  If I fail, I'll pass it to you ;)

**Comment by kngwyu** [comment]
@mvaled 
Thank you, let us know any question if you get stucked.

**Comment by mvaled** [comment]
@kngwyu 

I tried several things, without luck.  The reversed operator may itself return NotImplemented (which I think would be the case of our test), so I need to compare the result of the reversed call to NotImplemented.

The last commit (7d15e51ef7989a34402a06f8f77f1d3c56bc97c3) is the last attempt I've made so far.

**Comment by mvaled** [comment]
@kngwyu 

Well, the code of our `py_binary_fallback_num_func` is not being run for `obj == 1`, because `==` is implemented with `py_binary_reversed_num_func`.

I'm going to change that as well, while extracting the *upgrade* of NotImplemented to a TypeError in a macro.

**Comment by mvaled** [comment]
Forget about my previous comment.  Still doesn't work.  I'd need to know how `tp_richcompare` is handled.  

But I think @kngwyu could possibly fix this faster than I could.  I'm gonna close this PR and let you take it over, ok?

**Pull request closed without merging**
