### PR TITLE
Implement is_instance and is_subclass

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by fafhrd91** [comment]
I don't like idea of free functions. lets add/modify methods of `PyType` and add helper methods to `Python`

something like 
```rust

impl Python {

    pub fn is_instance<T: PyTypeObject>(obj: &PyObject) -> PyResult<bool>

}

**Comment by fafhrd91** [comment]
lets move actual is_instance and is_subclass code to PyType implementation

**Comment by messense** [comment]
Seems that `PyType` already have `is_instance` and `is_subtype_of` methods but using different CPython methods?

**Comment by fafhrd91** [comment]
I think your `is_instance` is better. could you check docs what is the difference between `PyObject_TypeCheck` and `PyObject_IsSubclass`

and rename `is_subtype_of` to `is_subclass`

**Comment by messense** [comment]
https://docs.python.org/3/c-api/type.html?highlight=pytype_issubtype#c.PyType_IsSubtype

`int PyType_IsSubtype(PyTypeObject *a, PyTypeObject *b)`
Return true if a is a subtype of b.

This function only checks for actual subtypes, which means that `__subclasscheck__()` is not called on b. Call `PyObject_IsSubclass()` to do the same check that `issubclass()` would do.

https://docs.python.org/3/c-api/object.html?highlight=pyobject_typecheck#c.PyObject_TypeCheck

`int PyObject_TypeCheck(PyObject *o, PyTypeObject *type)`
Return true if the object o is of type type or a subtype of type. Both parameters must be non-NULL.

The difference between `PyType_IsSubtype` and `PyObject_IsSubclass` is clearly, I am not sure about `PyObject_TypeCheck` and `PyObject_IsInstance`

**Comment by fafhrd91** [comment]
ok, replace it with your implementation

**Comment by fafhrd91** [comment]
lgtm

**Pull request merged**
