### PR TITLE
Multiple build matrix on Appveyor

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by fafhrd91** [comment]
seems something wrong with config, I see "Python 2.7.13" for python --version command

**Comment by messense** [comment]
Odd. I have a similar setup works fine...

**Comment by messense** [comment]
Ok, AppVeyor is really odd, force push seems causing it builds on wrong commit. Had to close and reopen to trigger a fresh build.

**Comment by messense** [comment]
Will revisit this later.

**Pull request merged**
