### PR TITLE
fix `PYO3_CONFIG_FILE` env var not requesting rebuilds

### PR DESCRIPTION
**Pull request by davidhewitt**
Candidate fix for #4757 

I will verify this downstream and also add tests as soon as I'm satisfied this is the likely solution.

### CODE REVIEW

**Comment by davidhewitt** [comment]
Both https://github.com/pydantic/jiter/pull/180 and https://github.com/pydantic/pydantic-core/pull/1570/commits/7b0190139bb200d0da696833ed03121e9d61f2a2 which test out #4758 are working as they should with this fix in place. So I am satisfied that this is the fix and we should get this merged asap.

**Comment by davidhewitt** [comment]
I pushed a crude test which should make it harder to make this mistake again. It would be nice to follow up with a more comprehensive way to test all cases of `pyo3-build-config` reading these env vars.

For now, is anyone available to review this? Otherwise I will merge in a few hours and start preparing the patch release.

**Comment by alexdotgov2** [comment]
(Hi, this is Alex's work github)

The fix looks prima facie reasonable to me, but I sadly don't have the time to deeply review.

I'm not a huge fan of the `cfg()` for tracking the env vars, but I'm not sure I have a better suggestion.

**Comment by alexdotgov2** [comment]
We should also use clippy to prohibit direct env var access and force people to go through the right internal functions -- https://github.com/sfackler/rust-openssl/commit/e5bd08f9be876e3ba760cf166eb9eddb74feebdd is an example of this pattern.

**Comment by davidhewitt** [comment]
Agreed, while it wouldn't have caught this particular error, in combination with a better testing strategy it might prevent future mistakes. Opened #4761 to track the follow-ups.

**Pull request merged**
