### PR TITLE
pyproto: remove deprecated feature

### PR DESCRIPTION
**Pull request by davidhewitt**
Removes `#[pyproto]` - quite a big purge of the codebase!

Might hold off on merging this just for a little bit in case 0.17 needs some quick fixes (just to avoid the bother of having to cherry-pick).

### CODE REVIEW

**Comment by mejrs** [comment]
`+41 −5,308` - love to see it.


 What about https://github.com/PyO3/pyo3/pull/2326#discussion_r857067605 ? You might be able to remove even more code 🙂

**Comment by davidhewitt** [comment]
Maybe, you mean converting over from `IntoPyCallbackOutput` to `IntoPyResult`? If possible I'd prefer to keep logic changes to a follow-up PR, as this huge -5000 diff (:tada:) means it'll be quite hard for reviewers to see relevant logic changes.

**Comment by mejrs** [comment]
Sounds good 👍

**Comment by davidhewitt** [comment]
With 0.17.1 out I'm going to merge this now so that it's easier for us to make new changes that we were blocked on before.

**Review by messense — APPROVED** [review]
🎊

**Pull request merged**
