### PR TITLE
release: 0.20.1

### PR DESCRIPTION
**Pull request by davidhewitt**
This is a patch release which picks various docs additions, some minor nonbreaking additions, and also a few fixes as 0.20.1.

I'd sort of hoped we wouldn't need to do this, but unfortunately we had the clippy warning in #3561 which is now stable in Rust 1.75. I think 0.21 is still a couple weeks away, so I think the ecosystem can benefit from having this pushed sooner.

Fixes https://github.com/rust-lang/rust-clippy/issues/12039

### CODE REVIEW

**Comment by davidhewitt** [comment]
I'm pretty certain that I'm going to have to fight CI, though with luck I picked all the necessary commits 🙈

**Comment by davidhewitt** [comment]
Assuming CI is green and I hear no concerns, I'll aim to put this live tomorrow evening.

**Comment by davidhewitt** [comment]
Release is live!

**Comment by Xuanwo** [comment]
Thanks a lot for your work!

**Pull request merged**
