### PR TITLE
Impl IntoPyObject for HashMap and BTreeMap

### PR DESCRIPTION
**Pull request by messense**
Why it's not implemented before? Is it safe to do so?

### CODE REVIEW

**Comment by fafhrd91** [comment]
should we also implement ToPyObject for `((k, v), (k, v), ... where k: ToPyObject, v: ToPyObject`?

**Comment by messense** [comment]
For `[(k, v), (k, v)...] where k: ToPyObject, v: ToPyObject`, it can collected into `HashMap/BTreeMap` with `FromIterator` trait. I am not sure about the tuple version.

**Comment by fafhrd91** [comment]
it is more about ergonomics, details doesn't matter

**Comment by fafhrd91** [comment]
something like `self.call_method(NoArgs, [(k1, v1), (k2, v2), ..])

**Comment by messense** [comment]
That seems nice. But should it be converted into `list[tuple]` or `dict`?

**Comment by fafhrd91** [comment]
Specifically for tuple with size 2 should be fine

**Comment by fafhrd91** [comment]
sorry, misread. we can introduce IntoPyDict trait similar to IntoPyTuple.

**Pull request merged**
