### PR TITLE
release: 0.21.2

### PR DESCRIPTION
**Pull request by davidhewitt**
WIP holding branch for cherry-picks for the 0.21.2 patch release. I think at least #4036 also needs fixing first, and also I'd like to see cryptography finish updating to 0.21 before we bother pushing another patch.

### CODE REVIEW

**Comment by alex** [comment]
We're tracking our progress here:
https://github.com/pyca/cryptography/issues/10676

It'll probably be at least a week or two for us to burn this down though.

**Comment by davidhewitt** [comment]
I think we've now collected quite a few fixes here and this is ready to be pushed; I'll publish this release on Tuesday unless I hear a reason to wait!

**Comment by Icxolu** [comment]
We forgot a deprecation working for `PySet::empty`, maybe that worth adding here?

**Review by LilyFoote — APPROVED** [review]

**Comment by davidhewitt** [comment]
> We forgot a deprecation working for `PySet::empty`, maybe that worth adding here?

Ah good catch, good idea! I'll take a look at that this evening hopefully if nobody opens a PR sooner...

**Pull request merged**
