### PR TITLE
docs: semantic change typo

### PR DESCRIPTION
**Pull request by digitalsentinel**
Thank you for contributing to PyO3!

By submitting these contributions you agree for them to be dual-licensed under PyO3's [MIT OR Apache-2.0 license](https://github.com/PyO3/pyo3#license).

Please consider adding the following to your pull request:
 - an entry for this PR in newsfragments - see [https://pyo3.rs/main/contributing.html#documenting-changes]
   - or start the PR title with `docs:` if this is a docs-only change to skip the check
 - docs to all new functions and / or detail in the guide
 - tests for all new or changed functions

PyO3's CI pipeline will check your pull request, thus make sure you have checked the `Contributing.md` guidelines. To run most of its tests
locally, you can run ```nox```. See ```nox --list-sessions```
for a list of supported actions.

### CODE REVIEW

**Comment by alex** [comment]
I'm reasonably certain this is not a typo, why do you think it is?

**Comment by digitalsentinel** [comment]
Sorry, perhaps I was hasty with my change, but this sentence threw me and still does. 

Perhaps necessary should be changed to sufficient?

When would  a `Py<T>` not be necessary for lifetime reason?

Happy to close, forget, and apologize for jumping to conclusions.

**Comment by birkenfeld** [comment]
`Py<T>` is "easier" to work with, because it does *not* carry a lifetime around. That is useful for storing in other `pyclasses` or long lived structs in general.

The sentence is correct, but maybe this version is better to understand?

"This means that `Bound<'py, T>` should usually be used whenever carrying this lifetime is acceptable, and `Py<T>` otherwise."

**Comment by digitalsentinel** [comment]
This is clearer to me.
Thanks!

**Comment by dsentinel** [comment]
> "This means that `Bound<'py, T>` should usually be used whenever carrying this lifetime is acceptable, and `Py<T>` otherwise."

Changed commit to use this wording.

**Pull request merged**
