### PR TITLE
Bump version to 0.9.0

### LINKED ISSUE #808: release non-alpha version of 0.9
release non-alpha version of 0.9

### PR DESCRIPTION
**Pull request by kngwyu**
Resolves #808

### CODE REVIEW

**Comment by birkenfeld** [comment]
@kngwyu I'd like to update the docstrings of pyo3 types to point to the new guide first. I can do it today.

**Comment by kngwyu** [comment]
@birkenfeld 
Thank you!
I'm willing to wait for that.

**Comment by birkenfeld** [comment]
Can we also import PyAny to the main crate namespace?

**Comment by kngwyu** [comment]
@birkenfeld 
I don't have any strong opinions about that.
They are hidden since https://github.com/PyO3/pyo3/commit/302c099a766a2a3759933b9c5da9c7ca90c91507 and left as is.
@konstin 
What kind of intention did you have for not exposing `types::*` in lib.rs?

**Comment by birkenfeld** [comment]
I think it makes sense to put the long list of concrete types there.

But if we want to enhance visibility of `PyAny` and make clear that it's an important type, counterpart to `PyObject`, it should be in the root/prelude.

**Comment by konstin** [comment]
The idea was to prevent the top level from becoming to cluttered with all the builtin types. But imo PyAny can also be the root namespace and/or the prelude.

**Comment by kngwyu** [comment]
@birkenfeld @konstin 
Thank you for the feedback!
I'll create a PR for `PyAny` later.

**Comment by kngwyu** [comment]
Now ready to release :)

**Comment by birkenfeld** [comment]
Thanks! Can you set a tag?

**Comment by kngwyu** [comment]
Sure, I made it now. https://github.com/PyO3/pyo3/releases/tag/v0.9.0

**Pull request merged**
