### PR TITLE
Remove dead code in macros backend

### PR DESCRIPTION
**Pull request by alex**
Thank you for contributing to PyO3!

### CODE REVIEW

**Review by davidhewitt — APPROVED** [review]
Thanks! See also #4010, let's merge this one and I'll tidy the other PR up later.

**Comment by alex** [comment]
Is https://github.com/PyO3/pyo3/actions/runs/8480976804/job/23237630151 a known flake? Don't see how it could be caused by this PR

**Comment by davidhewitt** [comment]
It makes sense to me why that's flaky, #4014 should resolve.

**Comment by alex** [comment]
I'm going to let the merge queue clear out before I re-add this.

**Comment by davidhewitt** [comment]
Yeah, need to think if there's anything else we can do to help CI run a little more efficiently...

**Comment by alex** [comment]
I filed a seperate bug as a place to ideate/track improvements.

**Pull request merged**
