### PR TITLE
Add more implementations of ExactSizeIterator when iterating built-in Python data structures.

### LINKED ISSUE #2673: implement `ExactSizeIterator` for list, set, frozenset and dict
it seems to be already implemented for tuple, would be great if it could be implemented for other common types.

Unless there's a good reason it's not already done?

### PR DESCRIPTION
**Pull request by adamreichold**
Closes #2673

### CODE REVIEW

**Review by davidhewitt — APPROVED** [review]
Thanks 👍

**Comment by samuelcolvin** [comment]
Would be great to get this released? in particular it should allow converting from a `PyList` to a `PyTuple` without an intermediate `vec`.

**Comment by davidhewitt** [comment]
My hope is to release 0.17.3 by the end of the week with all non-breaking changes and support for Python 3.11 verified by CI. Just need to work through the blockers first.

This change seems suitable for inclusion.

**Comment by samuelcolvin** [comment]
Great, thanks so much.

**Pull request merged**
