### PR TITLE
release: 0.18.1

### PR DESCRIPTION
**Pull request by davidhewitt**
We've collected a few useful fixes and additions since 0.18.0 was pushed live, so I suggest we cut a new release.

I've arbitrarily picked Tuesday to find a moment to push this. 

@samuelcolvin if you'd like to have #2912 in the release then let me know before Tuesday, we can wait a bit for that PR to be finished off first.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Thanks @davidhewitt.

#2912 should be complete, but TBH I'm not that bothered about including it, I can easily use the methods via `ffi` if I really need them.

#2914 is another matter - it would be great to get this included! I currently have numerous `xfail`s in pydantic-core related specifically to this. (I know #2914 looks more complicated, and unlike to be included, but I thought worth asking anyway)

**Comment by davidhewitt** [comment]
Sorry for the delay, family ill again, obviously Tuesday has flown past. I'll get rebasing this and I think #2914 needs to be included before we push, as there's a nasty bug there.

**Comment by samuelcolvin** [comment]
No problem, I know all about missing self imposed deadlines.

**Comment by davidhewitt** [comment]
Following merge of #2934 and #2937 I'll rebase this, with a view to releasing this evening.

**Comment by davidhewitt** [comment]
Release is live!

**Comment by samuelcolvin** [comment]
Amazing, thank you.

**Pull request merged**
