### PR TITLE
Use `try_for_each` in `into_py_dict`

### PR DESCRIPTION
**Pull request by bschoenmaeckers**
This applies the suggestion in https://github.com/PyO3/pyo3/pull/4493#discussion_r1783428131 to see if this will lead to any improved performance (or not 🤷‍♂️).

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks for following up with this! I think we actually lack benchmarks for this case (or at least I didn't spot any), so might need to add some? 🤔

**Comment by bschoenmaeckers** [comment]
The `dict_new` [benchmark](https://codspeed.io/PyO3/pyo3/benchmarks/pyo3-benches/benches/bench_dict.rs::benches::criterion_benchmark::dict_new?branchId=671b607387c057e77471f4fc) uses `into_py_dict` but does not show any difference.

**Comment by bschoenmaeckers** [comment]
I suspect it only has an advantage  on the free-threaded build because of the critical-section wrapping the whole loop.

**Review by davidhewitt — APPROVED** [review]
Ah, yes.

I think it makes sense to proceed to merge this; as I understand it, for complex iterators this is better for the optimizer and it's definitely better for our own free-threaded iterators!

**Pull request merged**
