### PR TITLE
Always use correct abi3 Python DLL name for MinGW

### PR DESCRIPTION
**Pull request by ravenexp**
Compiling an abi3 extension module for `x86_64-pc-windows-gnu` target
links to `python3.dll` import library when `PYO3_NO_PYTHON` is set
and to `python3.Y.dll` import library when `PYO3_NO_PYTHON` is not set.

All abi3 extensions should link to `python3.dll` on Windows,
as required by

https://www.python.org/dev/peps/pep-0384/#linkage

Update the code path for the case when `PYO3_NO_PYTHON` is not set
to yield the same Python DLL import library name.

### CODE REVIEW

**Comment by messense** [comment]
Close and reopen to trigger CI.

**Review by kngwyu — APPROVED** [review]
Sounds reasonable, thank you!

**Comment by MehdiChinoune** [comment]
On MSYS2 we have only libpythonX.Y.dll/dll.a libs.
Building python-cryptography fails because of this change.
`lld: error: unable to find library -lpython3`
`D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpython3: No such file or directory`

Is there a workaround to ask for libpythonX.Y?

**Comment by davidhewitt** [comment]
I think you could write a custom `PYO3_CONFIG_FILE` (see https://pyo3.rs/v0.16.4/building_and_distribution.html#advanced-config-files).

You might also consider filling an upstream msys2 bug?

**Comment by ravenexp** [comment]
It links to `python3.dll.a` because you are trying to compile an `abi3` extension, which do not seem to be supported by the MSYS2 Python distribution.

If you disable the `abi3` feature it should link to the version-specific library the PyO3 build script discovers via `_sysconfigdata*.py` parsing. This should work on MSYS2, I think. If it doesn't, please open an issue.

**Comment by davidhewitt** [comment]
@ravenexp what you say is true, but I think in practice it should also be safe to link the version-specific library using only the abi3 apis? The build just wouldn't be portable between versions due to the link name.

**Comment by ravenexp** [comment]
> @ravenexp what you say is true, but I think in practice it should also be safe to link the version-specific library using only the abi3 apis? The build just wouldn't be portable between versions due to the link name.

I also think it should work, but it's kinda.. pointless. You still need to build one extension DLL per supported Python version, so why give up performance by restricting PyO3 to the stable API?

**Comment by MehdiChinoune** [comment]
> If you disable the `abi3` feature it should link to the version-specific library the PyO3 build script discovers via `_sysconfigdata*.py` parsing. This should work on MSYS2, I think.

I looks like It links after disabling `abi3`.
>If it doesn't, please open an issue.

It couldn't find `cryptography_rust.so` (unix extension).

`error: Rust build failed; unable to find any *cryptography_rust.so in C:\_\mingw-w64-python-cryptography\src\cryptography-37.0.4\src\rust\target/release`

Should I open an issue?

**Comment by davidhewitt** [comment]
Was probably fixed by https://github.com/PyO3/setuptools-rust/pull/267 - just needs a new `setuptools-rust` release.

**Pull request merged**
