### PR TITLE
Add PyEval_SetProfile, PyEval_SetTrace

### PR DESCRIPTION
**Pull request by aviramha**
Not sure if I missed anything, I relied on existing infra to understand what needs to be done.
Feedback will be appreciated.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thanks!
Could you please consider placing those on `ceval.rs` since they are originally in `ceval.h`?
Also, it would be better if we have
```rust
pub type Py_tracefunc = extern "C" fn(
    obj: *mut PyObject,
    frame: *mut PyFrameObject,
    what: c_int,
    arg: *mut PyObject,
) -> c_int;
```
in `pystate.rs`.

**Comment by aviramha** [comment]
@kngwyu Thanks for the review! I tried to do what you have suggested but have failed due to lack of Rust/FFI experience 👍 
I'll change it ASAP.

**Comment by aviramha** [comment]
Done!

**Review by kngwyu — APPROVED** [review]
Thanks!

**Pull request merged**
