### PR TITLE
guide: better document negative index behavior w.r.t. PySequence

### LINKED ISSUE #2601: docs: `#[pyclass(sequence)]` does not make Python add the sequence length to negative indexes
### Bug Description

https://pyo3.rs/v0.17.1/class/protocols.html#mapping--sequence-types

> Use the #[pyclass(sequence)] annotation to instruct PyO3 to fill the sq_length slot instead of the mp_length slot for __len__. This will help libraries such as numpy recognise the class as a sequence, however will also cause CPython to automatically add the sequence length to any negative indices before passing them to __getitem__. (__getitem__, __setitem__ and __delitem__ mapping slots are still used for sequences, for slice operations.)

What actually happens is that negative indices are passed as is to `__getitem__`.

I guess this happens because PyO3 only fills the mapping slot for `__getitem__`, and the negative index correction thing only happens when calling the sequence slot for `__getitem__`.

### Steps to Reproduce

Minimal reproduction:

```rust
use pyo3::prelude::*;                                  
                                                       
#[pyclass(sequence)]                                   
struct MyList;                                         
                                                       
#[pymethods]                                           
impl MyList {                                          
    #[new]                                             
    fn new() -> MyList {                               
        MyList {}                                      
    }                                                  
                                                       
    fn __len__(&self) -> usize {                       
        42                                             
    }                                                  
                                                       
    fn __getitem__(&self, idx: isize) -> bool {        
        assert!(idx >= 0);                             
        true                                           
    }                                                  
}                                                      
                                                       
#[pymodule]                                            
fn testmod(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<MyList>()?;                          
    Ok(())                                             
}                                                      
```

### Backtrace

```shell
>>> from testmod import MyList
>>> a = MyList()
>>> a[-1]
thread '<unnamed>' panicked at 'assertion failed: idx >= 0', src/lib.rs:18:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: assertion failed: idx >= 0
>>> a[0]
True
```
```


### Your operating system and version

Arch Linux

### Your Python version (`python --version`)

Python 3.10.6

### Your Rust version (`rustc --version`)

rustc 1.63.0

### Your PyO3 version

0.17.1

### How did you install python? Did you use a virtualenv?

pacman

Yes

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by birkenfeld**
Fixes #2601

### CODE REVIEW

**Comment by davidhewitt** [comment]
Possibly worth mentioning that this negative index handling only applies with `#[pyclass(sequence)]`?

**Comment by birkenfeld** [comment]
Updated.

**Comment by birkenfeld** [comment]
I don't understand the test failure...

**Comment by birkenfeld** [comment]
@messense I see that maturin 0.14 has been released recently. Can this be a problem with it?

**Comment by messense** [comment]
> @messense I see that maturin 0.14 has been released recently. Can this be a problem with it?

Yes, it's resolved by https://github.com/PyO3/maturin/pull/1279.

For now you can pin maturin to 0.13.x in 
https://github.com/PyO3/pyo3/blob/3408cc420052b9a61cbe535c9f7229982f0d20a5/pytests/noxfile.py#L12

**Comment by birkenfeld** [comment]
Do we need to do this or will the fix be released soon?

**Comment by messense** [comment]
> Do we need to do this or will the fix be released soon?

I'll cut a new release now, but it's good idea to add a version constraint there anyway.

**Review by davidhewitt — APPROVED** [review]
Thanks 👍

**Pull request merged**
