### PR TITLE
Fix chrono deprecation warning

### PR DESCRIPTION
**Pull request by bschoenmaeckers**

### CODE REVIEW

**Review by Icxolu — APPROVED** [review]

**Comment by Icxolu** [comment]
I think we need to bump `chrono`s minimum version slightly for this.

**Comment by ngoldbaum** [comment]
The merge queue CI failed, see https://github.com/PyO3/pyo3/actions/runs/12264475737/job/34218435360#step:8:340

The `MIN` and `MAX` constants were just added in the most recent version of `chrono`, so I don't think bumping the minimum version is correct.

Maybe we should open an issue in `chrono` asking for a way to spell this that works on older `chrono` versions.

**Comment by Icxolu** [comment]
Ah, I didn't realize that they are _only_ available in the lastest patch. In that case it really seems unfortunate to only support that version of `chrono`... Maybe we just `#[allow(deprecated)]` for now and bump the minimum version in the future?

**Comment by ngoldbaum** [comment]
`[allow(deprecated)]` is a bit of a blunt hammer but I think it's the most reasonable thing to do given that `cargo test` doesn't support runtime skips.

**Comment by ngoldbaum** [comment]
@bschoenmaeckers hope you don't mind me pushing to your branch, I'd like to get CI unblocked today :)

**Review by Icxolu — APPROVED** [review]

**Comment by bschoenmaeckers** [comment]
> @bschoenmaeckers hope you don't mind me pushing to your branch, I'd like to get CI unblocked today :)

Go ahead!

**Pull request merged**
