### PR TITLE
use FFI calls for refcounting on all abi3 versions

### PR DESCRIPTION
**Pull request by davidhewitt**
As per https://github.com/PyO3/pyo3/issues/4311#issuecomment-2216740704

The idea is that we can mitigate issues around 3.12's immortal objects and wonky CPython assertions by backporting the stable ABI change to use FFI calls for refcounting from 3.12 all the way back to our supported version of 3.8.

cc @alex - you might be interested in this for the possible performance impact on cryptography (though this impact would be felt eventually anyway).

### CODE REVIEW

**Comment by alex** [comment]
Our benchmarking infra isn't particularly high fidelity, but this change looks like it's within the noise floor for us: https://github.com/pyca/cryptography/actions/runs/9856363207?pr=11232

**Comment by davidhewitt** [comment]
👍 

cc @mgorny are you willing to test one of the problematic packages with this branch? If so, I'm tempted to merge it for the simplification it brings.

**Comment by mgorny** [comment]
I'll try on rustworkx in a minute.

**Comment by mgorny** [comment]
And confirmed! Without the patch, `rustworkx` crashes; with the patch, it passes all tests.

**Comment by davidhewitt** [comment]
Great! In which case if fellow PyO3 maintainers are happy, I propose to merge this and ship as 0.22.2 (maybe also with #4321 when that's done).

**Comment by davidhewitt** [comment]
Thanks @mgorny and @alex for testing!

**Comment by davidhewitt** [comment]
Having heard no concerns, I think let's move ahead with this.

**Comment by davidhewitt** [comment]
cc @encukou @vstinner - with this patch PyO3 is using `Py_IncRef` or `_Py_IncRef` (and similar for decref) for all stable ABI versions.

**Pull request merged**
