### PR TITLE
ci: configure bors

### PR DESCRIPTION
**Pull request by davidhewitt**
Just for the moment seeing how to interact with bors, will experiment with CI setup in #2710 once I understand it.

### CODE REVIEW

**Comment by davidhewitt** [comment]
bors try

**Comment by adamreichold** [comment]
> ## try
> 
> Timed out.

I think our branch specification is missing the `trying` and `staging` branches used by bors:

```yaml
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
```

**Comment by davidhewitt** [comment]
Yes, that was the conclusion that I'd come to too. I'll push that first and then see what a try gives, before perhaps moving part of the pipeline to _only_ run on bors.

**Comment by davidhewitt** [comment]
bors try

**Comment by davidhewitt** [comment]
bors try

**Comment by messense** [comment]
bors is probably still waiting for something, causing https://github.com/PyO3/pyo3/pull/2771#issuecomment-1323797551

bors try-

**Comment by davidhewitt** [comment]
bors try-

**Pull request closed without merging**
