### PR TITLE
actions: cache rust builds

### PR DESCRIPTION
**Pull request by davidhewitt**
Hopefully this will add some much-needed performance improvements to our CI times!

### CODE REVIEW

**Comment by davidhewitt** [comment]
Hmm strange. It cuts the CI times by about 50%. But there seem to be random bugs on macOS, and also I had an issue the first time where some jobs randomly failed in the post-run cache job (I think because too much got uploaded to new cache all at the same time).

So I don't really know whether the speedup, while nice, is worth the additional complexity...

**Review by messense — APPROVED** [review]

**Comment by kngwyu** [comment]
I don't think we need to merge this ASAP. Optimistically, one of us will find the workaround eventually.

**Comment by davidhewitt** [comment]
> I don't think we need to merge this ASAP. Optimistically, one of us will find the workaround eventually.

Even though we can't yet enable for macOS, I think there's value in merging this now. Github actions seems to have a limit to the number of jobs running across all PRs in parallel, so when several PRs are pushed close together it can take some time for all the CI to run.

If we cache the windows and linux jobs, we'll get through all of these jobs faster, so we get feedback on CI faster.

**Review by kngwyu — APPROVED** [review]
OK, I didn't check that you added `if: matrix.platform.os != 'macOS-latest'`

**Comment by messense** [comment]
Looks like you can workaround the macOS cache issue by using `gnu-tar`, see https://github.com/PyO3/maturin/pull/493

**Pull request merged**
