### PR TITLE
pyfunction: use METH_NOARGS for no-argument functions

### PR DESCRIPTION
**Pull request by birkenfeld**
As suggested in #1607.
    
If I ran the benchmarks correctly, this shaves only about 5ns from
the noargs case.  But since it's relatively easy to do...

### CODE REVIEW

**Review by davidhewitt — APPROVED** [review]
This is great, thanks!

On my machine it actually seems to reduce by more like 10ns, and more excitingly I now measure our no-args case to be pretty much equal to the Python one!

**Comment by birkenfeld** [comment]
Funny - the no-args Python was already slower before in my benchmarks (from `tox -e py`).

**Comment by davidhewitt** [comment]
Curious! What OS / Python version are you measuring on?

**Comment by birkenfeld** [comment]
This is on Linux/Py3.9 and a early Ryzen 8-core.

`main` after merge:
```
---------------------------------------------------------------------------------------------- benchmark: 6 tests ---------------------------------------------------------------------------------------------
Name (time in ns)                Min                    Max                  Mean              StdDev                Median                IQR             Outliers  OPS (Kops/s)            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_no_args                101.6509 (1.0)         701.4653 (1.91)       112.4121 (1.0)       10.0457 (1.02)       111.8609 (1.0)       6.0468 (1.44)   15267;14966    8,895.8367 (1.0)      197981          43
test_no_args_py             125.1101 (1.23)        367.0299 (1.0)        137.9458 (1.23)       9.8136 (1.0)        137.0098 (1.22)      4.2099 (1.0)      9504;9103    7,249.2228 (0.81)      71013         100
test_args_and_kwargs_py     534.0000 (5.25)      4,429.3993 (12.07)      603.0717 (5.36)      39.9979 (4.08)       599.1023 (5.36)      4.8982 (1.16)     3616;6009    1,658.1777 (0.19)     144280          10
test_mixed_args_py          705.1014 (6.94)      4,477.4002 (12.20)      860.4933 (7.65)      60.2558 (6.14)       853.1002 (7.63)     24.9973 (5.94)     6949;7788    1,162.1241 (0.13)     116687          10
test_args_and_kwargs        809.9887 (7.97)     14,570.9782 (39.70)      933.1094 (8.30)     147.5474 (15.03)      929.9838 (8.31)     30.0060 (7.13)     1119;7158    1,071.6857 (0.12)     142026           1
test_mixed_args             950.0072 (9.35)     37,642.9816 (102.56)   1,094.5140 (9.74)     193.4248 (19.71)    1,089.9967 (9.74)     39.9887 (9.50)     1529;6015      913.6475 (0.10)     110486           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

before:
```
----------------------------------------------------------------------------------------------- benchmark: 6 tests -----------------------------------------------------------------------------------------------
Name (time in ns)                Min                     Max                  Mean                StdDev                Median                IQR             Outliers  OPS (Kops/s)            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_no_args                102.4384 (1.0)          961.8049 (1.03)       112.6693 (1.0)          8.7736 (1.20)       111.9511 (1.0)       5.3658 (3.16)   13426;12566    8,875.5310 (1.0)      196464          41
test_no_args_py             122.4098 (1.19)         937.1800 (1.0)        137.1851 (1.22)         7.2829 (1.0)        137.2100 (1.23)      1.7000 (1.0)      5494;7658    7,289.4191 (0.82)      58821         100
test_args_and_kwargs_py     535.9994 (5.23)      25,806.3024 (27.54)      609.1173 (5.41)       253.2263 (34.77)      595.9999 (5.32)     40.0003 (23.53)   1897;13039    1,641.7200 (0.18)     146822          10
test_mixed_args_py          698.9983 (6.82)       4,800.4003 (5.12)       768.7399 (6.82)        60.5227 (8.31)       763.9988 (6.82)     40.0993 (23.59)   10060;8183    1,300.8300 (0.15)     116266          10
test_args_and_kwargs        800.0061 (7.81)      23,622.0076 (25.21)      908.6107 (8.06)       185.8825 (25.52)      900.0069 (8.04)     79.9773 (47.05)    3022;6903    1,100.5813 (0.12)     133852           1
test_mixed_args             929.9838 (9.08)     510,565.0052 (544.79)   1,122.1239 (9.96)     2,061.4126 (283.05)   1,050.0080 (9.38)     51.0190 (30.01)    216;11263      891.1672 (0.10)     114417           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by birkenfeld** [comment]
In this run, no difference at all ?!

**Comment by davidhewitt** [comment]
Hmm interesting; this is what I get on Ubutntu 20.04 / Python 3.9.1 (under WSL2) with a Core i7-10750H laptop chip (as long as I have the AC adapter connected):

`main` after merge:

```
-------------------------------------------------------------------------------------------- benchmark: 6 tests -------------------------------------------------------------------------------------------
Name (time in ns)                Min                    Max                Mean              StdDev              Median                IQR             Outliers  OPS (Mops/s)            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_no_args                 58.0000 (1.0)         945.0000 (1.0)       63.2198 (1.0)       24.0871 (1.0)       60.0000 (1.0)       1.0000 (>1000.0) 2834;21219       15.8178 (1.0)      161291         100
test_no_args_py              58.0000 (1.0)       2,644.0000 (2.80)      68.0741 (1.08)      29.8120 (1.24)      63.0000 (1.05)      3.0000 (>1000.0)  5145;6328       14.6899 (0.93)     151516         100
test_args_and_kwargs_py     218.1818 (3.76)     45,900.0000 (48.57)    244.2523 (3.86)     173.3439 (7.20)     227.2727 (3.79)      4.5455 (>1000.0)  3746;9683        4.0941 (0.26)     196079          22
test_mixed_args_py          294.1176 (5.07)      4,711.7647 (4.99)     318.7492 (5.04)     122.0044 (5.07)     300.0000 (5.00)      5.8824 (>1000.0) 3624;23926        3.1373 (0.20)     192308          17
test_args_and_kwargs        299.9998 (5.17)     37,600.0000 (39.79)    413.0619 (6.53)     633.4833 (26.30)    400.0001 (6.67)      0.0002 (1.0)      296;19100        2.4209 (0.15)     133334           1
test_mixed_args             399.9999 (6.90)     34,400.0000 (36.40)    478.6762 (7.57)     537.2325 (22.30)    499.9999 (8.33)     99.9999 (>1000.0)    403;927        2.0891 (0.13)     153847           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

before:

```
-------------------------------------------------------------------------------------------- benchmark: 6 tests --------------------------------------------------------------------------------------------
Name (time in ns)                Min                    Max                Mean              StdDev              Median                 IQR             Outliers  OPS (Mops/s)            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_no_args_py              59.0000 (1.0)         937.0000 (1.0)       66.3024 (1.0)       26.5731 (1.0)       62.0000 (1.0)        1.0000 (1.0)     3799;29280       15.0824 (1.0)      158731         100
test_no_args                 63.0000 (1.07)      1,000.0000 (1.07)      72.6899 (1.10)      32.8498 (1.24)      67.0000 (1.08)       4.0000 (4.00)     5501;6757       13.7571 (0.91)     147059         100
test_args_and_kwargs_py     222.7273 (3.78)      3,118.1818 (3.33)     255.2286 (3.85)     122.0252 (4.59)     236.3636 (3.81)       9.0909 (9.09)     5333;8100        3.9181 (0.26)     192308          22
test_mixed_args_py          294.1176 (4.99)      5,411.7647 (5.78)     340.0529 (5.13)     175.3139 (6.60)     311.7647 (5.03)      17.6470 (17.65)    5473;6834        2.9407 (0.19)     192308          17
test_args_and_kwargs        299.9998 (5.08)     53,199.9999 (56.78)    409.0918 (6.17)     787.7994 (29.65)    399.9999 (6.45)     100.0001 (100.00)    541;2134        2.4444 (0.16)     166667           1
test_mixed_args             325.0000 (5.51)     37,340.0000 (39.85)    369.2841 (5.57)     201.6239 (7.59)     350.0000 (5.65)      20.0000 (20.00)    2862;3992        2.7079 (0.18)     140846          20
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

There's clearly an improvement for me!

**Comment by birkenfeld** [comment]
Well, then I'm happy :)

**Pull request merged**
