### PR TITLE
Reactivate coverage on CI

### LINKED ISSUE #279: Reactivate coverage on ci
The coverage task was commented out on travis because kcov was broken at some point. It should be reactivated and maybe also stop including the test files in the coverage stats. The task itself is easy (trial and error bash scripting), but cumbersome because it likely takes a few iterations with waiting on ci.

### PR DESCRIPTION
**Pull request by Alexander-N**
Closes #279

### CODE REVIEW

**Comment by konstin** [comment]
Thank you for tackling this! 

Could you add the pyo3cls and pyo3-derive-backend to the fileset and `$HOME/.cargo/bin/` to the travis? Otherwise it's looking good

**Comment by Alexander-N** [comment]
> Could you add the pyo3cls and pyo3-derive-backend to the fileset

Sure, how about just changing `find . -path ./target/debug/pyo3-\*` to `find . -path ./target/debug/pyo3\*`?

> `$HOME/.cargo/bin/` to the travis?

You mean to the travis cache? I thought that was covered by https://github.com/PyO3/pyo3/blob/88924a3122723b34fe6b4503668a8dc3b66c06e7/.travis.yml#L5-L7

**Comment by konstin** [comment]
> Sure, how about just changing find . -path ./target/debug/pyo3-\* to find . -path ./target/debug/pyo3\*?

Sound good

> You mean to the travis cache? I thought that was covered by 

You're right, that's already covered by `cargo: true`

**Comment by konstin** [comment]
Could you [squash](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) your commits? Otherwise it's looking good.

**Comment by konstin** [comment]
Thank you!

**Pull request merged**
