### PR TITLE
release: 0.22.1

### PR DESCRIPTION
**Pull request by davidhewitt**
I think this is everything so far that we've observed worth shipping quick fixes for on 0.22.

I'll put live tomorrow unless there's cause to delay.

### CODE REVIEW

**Review by alex — APPROVED** [review]
Thanks!

**Comment by alex** [comment]
Looks like a known flake impacting pypy 3.8 (fixed in 3.9/3.10). I think we can just re-run?

**Comment by davidhewitt** [comment]
I will merge now and complete the release tomorrow I think.

**Comment by davidhewitt** [comment]
Release is live!

**Pull request merged**
