### PR TITLE
Add support for converting to and from malachite's Natural and Integer types.

### PR DESCRIPTION
**Pull request by amamic1803**
Malachite is yet another big num crate written in Rust.
I use it because it seems to be more performant than others, so I added support for converting Python integer to and from Natural and Integer types in malachite.

I used conversion code for num-bigint as a template and then modified it so that it works for malachite.

The interesting thing about malachite is that it can work with both 32-bit and 64-bit limbs so I implemented both (added separate feature flag for 32bit case).

Tests are also modified from code for num-bigint, they are all passing correctly.
Relevant features combinations for tests are:
```
cargo test --lib conversions::malachite --features malachite
cargo test --lib conversions::malachite --features malachite-32bit
cargo test --lib conversions::malachite --features malachite --features abi3
cargo test --lib conversions::malachite --features malachite-32bit --features abi3
```

Regards

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks for the PR, and sorry it's taken me a couple days to get to an initial response.

This PR looks thoughtfully implemented, however, I must be honest: I'm reluctant to accept this feature because I think that it sets a precedent to allow a lot of similar crates, which could bloat PyO3 maintainer burden a lot. `num-bigint` is not the only crate in the "bignum" space, however it's the most widely used (and is actively maintained).

This is the first time I've heard of malachite, and while it looks promising (and I can believe it's faster), it has 100x smaller download volume.

One of the main reasons to accept these features is ergonomics for PyO3 users for common use cases. If `malachite` is wanted for performance, not having this PR won't prevent users from using it with PyO3, they just have to use tricks like newtypes or `#[pyo3(from_py_with)]`.

I think a part of me also feels like if performance is the only differentiator between `malachite` and `num-bigint`, then the ecosystem would be better served right now by investment in helping `num-bigint` be faster, rather than by PyO3 aiding in fragmentation.

If there are reasons beyond performance for `malachite` to be considered, then that would of course strengthen the argument.

**Comment by amamic1803** [comment]
I understand your concerns, but many of the stuff used to implement these conversions is private in PyO3 and therefore I can't use them to implement conversion outside of PyO3 itself.

**Comment by adamreichold** [comment]
> I understand your concerns, but many of the stuff used to implement these conversions is private in PyO3 and therefore I can't use them to implement conversion outside of PyO3 itself.

Can you identify the parts which are unavailable downstream so we can discuss whether they can be made accessible in the public API as general tools?

**Comment by amamic1803** [comment]
Well, I managed to convert everything to use public api of PyO3, the only thing that I can't find a public counterpart is `err::error_on_minusone`. I avoided using that by manually comparing the return value to minus one and than fetching error manually if needed. That should be okay, right?

**Comment by adamreichold** [comment]
> That should be okay, right?

Yes, certainly. `error_on_minusone` is purely an internal helper function codifying the existing convention used by many (but not all) Python C API entry points. Open-coding this or copying the helper function appears appropriate IMHO.

(Exposing it is a bit weird as it straddles the boundary between the `pyo3` and `pyo3-ffi` crates: It implements a convention that conceptually belongs to `pyo3-ffi` but it uses the high-lever error types from `pyo3`.)

**Comment by amamic1803** [comment]
Thanks for clarification. I will close this PR and make another PR directly to malachite crate where I will directly implement needed traits for conversions on its bignum types.

Just one more quick question, my code needs to know when PyO3 uses `abi3` (`Py_LIMITED_API`). I did as instructed [here](https://pyo3.rs/v0.20.3/building_and_distribution/multiple_python_versions#using-pyo3-build-config), but I'm wondering is there anything else I should do. Since I'm writing this in a malachite crate, typical user usage scenario would be adding malachite and PyO3 to their `Cargo.toml` and maybe setting the `abi3` feature for PyO3, will my implementation in malachite crate see this through `Py_LIMITED_API`?

**Comment by adamreichold** [comment]
> Just one more quick question, my code needs to know when PyO3 uses abi3 (Py_LIMITED_API). I did as instructed [here](https://pyo3.rs/v0.20.3/building_and_distribution/multiple_python_versions#using-pyo3-build-config), but I'm wondering is there anything else I should do. Since I'm writing this in a malachite crate, typical user usage scenario would be adding malachite and PyO3 to their Cargo.toml and maybe setting the abi3 feature for PyO3, will my implementation in malachite crate see this through Py_LIMITED_API?

Due to unification of dependencies, this is how it should work. (Meaning the top-level `pyo3` dependency would use the same instance of `pyo3-build-config` as the transitive `pyo3` dependency of `malachite` and hence end up with the correct build configuration.)

**Comment by amamic1803** [comment]
Thanks for all the help!

**Comment by davidhewitt** [comment]
No problem, sorry that we felt this was not right for merging to PyO3 at this time!

**Pull request closed without merging**
