### PR TITLE
Make ci happy

### PR DESCRIPTION
**Pull request by mejrs**

### CODE REVIEW

**Comment by davidhewitt** [comment]
👍 thanks for this!

**Comment by mejrs** [comment]
Weird.
```
 ---- gc_integration stdout ----
thread 'gc_integration' panicked at 'assertion failed: drop_called.load(Ordering::Relaxed)', tests\test_gc.rs:129:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\panicking.rs:100
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\panicking.rs:50
   3: test_gc::gc_integration
             at .\tests\test_gc.rs:129
   4: test_gc::gc_integration::closure$0
             at .\tests\test_gc.rs:105
   5: core::ops::function::FnOnce::call_once<test_gc::gc_integration::closure$0,tuple$<> >
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
   6: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    gc_integration
```
https://github.com/PyO3/pyo3/runs/4463849911?check_suite_focus=true

**Comment by mejrs** [comment]
I reran the workflow and it works now, so I guess I'll go ahead and merge this 🤷

**Comment by davidhewitt** [comment]
Yep that's totally fine! Thanks again!

**Pull request merged**
