### PR TITLE
silence deprecation warning for enum with custom `__eq__`

### LINKED ISSUE #4687: no way to disable implicit equality warning for enum
### Bug Description

I have a pyclass+enum to generate a enum class, and I want it to behavoie like `enum.Enum`, so I write a `__eq__` method to support both `Booking.STRICT == Booking.STRICT` and `Booking.STRICT == "STRICT"`, so I use `#[pyclass]` only

And it cause a warning ``warning: use of deprecated constant `base::Booking::__pyo3__generated____richcmp__::DEPRECATION`: Implicit equality for simple enums is deprecated. Use `#[pyclass(eq, eq_int)` to keep the current behavior.`` and there is no way to disable it.

```rs
#[pyclass]
#[derive(PartialEq)]
pub enum Booking {
    STRICT,
    #[allow(non_camel_case_types)]
    STRICT_WITH_SIZE,
    None,
    AVERAGE,
    FIFO,
    LIFO,
    HIFO,
}

#[pymethods]
impl Booking {
    // make it behave like enum.Enum
    #[getter]
    fn name(&self) -> &str {
        return self.__str__();
    }

    #[getter]
    fn value(&self) -> &str {
        return self.__str__();
    }

    // to support both `Booking.STRICT == Booking.STRICT` and `Booking.STRICT == "STRICT"`
    fn __eq__(&self, other: &Bound<'_, PyAny>) -> bool {
        if let Ok(s) = other.extract::<&str>() {
            return s == self.__str__();
        }

        if let Ok(b) = other.downcast::<Self>() {
            let other = &*b.borrow();
            return self == other;
        }

        return false;
    }

    fn __str__(&self) -> &str {
        match self {
            Booking::STRICT => "STRICT",
            Booking::STRICT_WITH_SIZE => "STRICT_WITH_SIZE",
            Booking::None => "None",
            Booking::AVERAGE => "AVERAGE",
            Booking::FIFO => "FIFO",
            Booking::LIFO => "LIFO",
            Booking::HIFO => "HIFO",
        }
    }
}
```

### Steps to Reproduce

copy paste code and build with pyo3 0.22.6

```text
task: [build] cargo build
   Compiling beancount v0.0.0 (C:\Users\Trim21\proj\beancount)
warning: use of deprecated constant `base::Booking::__pyo3__generated____richcmp__::DEPRECATION`: Implicit equality for simple enums is deprecated. Use `#[pyclass(eq, eq_int)` to keep the current behavior.
  --> src\base.rs:84:1
   |
84 | #[pyclass]
   | ^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in the attribute macro `pyclass` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `beancount` (lib) generated 1 warning                                                                                                                            
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.33s

```

### Backtrace

_No response_

### Your operating system and version

win10

### Your Python version (`python --version`)

Python 3.12.7

### Your Rust version (`rustc --version`)

rustc 1.82.0 (f6e511eec 2024-10-15)

### Your PyO3 version

0.22.6

### How did you install python? Did you use a virtualenv?

scoop, yes

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by davidhewitt**
Fixes #4687 

This adjusts the deprecation warning so that it's conditionally emitted using good old auto ref specialization, so that if the user provides `__eq__` (or any other `__richcmp__` component) then the deprecation warning is not emitted.

### CODE REVIEW

**Review by Icxolu — COMMENTED** [review]
Ah, very clever! This seems much nicer than an opt-out option. (But I'm still happy once we can remove all of this again 🙃)

It doesn't work however with a manual `__richcmp__` implementation directly. From a quick test we could do something like to following to catch that as well:

```patch
diff --git a/pyo3-macros-backend/src/pymethod.rs b/pyo3-macros-backend/src/pymethod.rs
index 1254a8d51..a5993c981 100644
--- a/pyo3-macros-backend/src/pymethod.rs
+++ b/pyo3-macros-backend/src/pymethod.rs
@@ -1348,6 +1348,13 @@ impl SlotDef {
         )?;
         let name = spec.name;
         let holders = holders.init_holders(ctx);
+
+        let dep = if method_name == "__richcmp__" {
+            quote! { impl #pyo3_path::impl_::pyclass::HasCustomRichCmp for #cls {} }
+        } else {
+            TokenStream::default()
+        };
+
         let associated_method = quote! {
             #[allow(non_snake_case)]
             unsafe fn #wrapper_ident(
@@ -1355,6 +1362,7 @@ impl SlotDef {
                 _raw_slf: *mut #pyo3_path::ffi::PyObject,
                 #(#arg_idents: #arg_types),*
             ) -> #pyo3_path::PyResult<#ret_ty> {
+                #dep
                 let function = #cls::#name; // Shadow the method name to avoid #3017
                 let _slf = _raw_slf;
                 #holders
```

**Comment by davidhewitt** [comment]
Ah, good catch 👍 

> (But I'm still happy once we can remove all of this again 🙃)

Haha yes indeed, we can probably delete this next week after the 0.23 branch is cut and released!

**Review by Icxolu — APPROVED** [review]

**Comment by Icxolu** [comment]
Just pushed a commit to fix ci (allow `non_local_definitions` and bless ui tests)

**Comment by davidhewitt** [comment]
Thanks 🙏

**Pull request merged**
