### PR TITLE
Avoid using CString where unnecessary

### PR DESCRIPTION
**Pull request by birkenfeld**
Use APIs that take a Python string instead of those taking a C string,
which are a convenience in C but require an unncessary allocation
for us.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thanks!
The CI failure in PyPy looks weird... :thinking: 
Maybe we need `#[cfg_attr(PyPy, link_name = "PyPyImport_Import")]`?

**Comment by birkenfeld** [comment]
Looks like the rustup CDN is currently flaky...

**Comment by davidhewitt** [comment]
Latest failure looks specific to pypy on windows, symbol not included only on that build? Perhaps worth posting an issue upstream?

**Comment by kngwyu** [comment]
I confirmed that ` error LNK2019: unresolved external symbol _PyPyModule_NewObject referenced ` is the problem and will some investigation tomorrow.

**Comment by kngwyu** [comment]
It looks like that pypy doesn't have `PyModule_NewObject`: https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/module/cpyext/modsupport.py

**Comment by birkenfeld** [comment]
Is that a PyPy bug, or should I remove that one from here?

**Comment by kngwyu** [comment]
> Is that a PyPy bug, or should I remove that one from here?

I'm not sure it's a bug or intended, but at least we should use `#[cfg(PyPy)]` if we want to use `PyModule_NewObject`.

**Comment by birkenfeld** [comment]
well, since it's only an optimization I removed that one.

**Review by kngwyu — APPROVED** [review]
Thanks!

**Pull request merged**
