### PR TITLE
Actually set target when running Clippy builds.

### PR DESCRIPTION
**Pull request by adamreichold**

### CODE REVIEW

**Comment by adamreichold** [comment]
Sorry, will not be able to fix all the Clippy stuff that is surfaced by setting the target today. If someone wants to continue and take over the branch, please feel free. Otherwise, I'll try to continue this tomorrow evening...

**Comment by davidhewitt** [comment]
Wow, great catch! I'm sure this can wait until tomorrow, I'm also off to bed 😅

**Comment by adamreichold** [comment]
Ok, should be good to review now.

**Review by davidhewitt — APPROVED** [review]
LGTM, thanks!

bors r+

**Pull request merged**
