### PR TITLE
Fix flaky tests

### LINKED ISSUE #386: GIL tests are flaky
The following tests fail randomly, for example in https://travis-ci.org/PyO3/pyo3/jobs/501186502:
* `gil::test::test_owned`
* `gil::test::test_owned_nested`
* `gil::test::test_pyobject_drop`

The reason seems to be that they all take references of the empty Python tuple and make assertions for the expected reference count. This can fail if the tests are executed in parallel.

### PR DESCRIPTION
**Pull request by Alexander-N**
The tests were flaky because they took references to the empty tuple
which is a singleton. Use a unique object for each test to make them
independent.

Closes #386

### CODE REVIEW

**Comment by kngwyu** [comment]
I don't like using redundant `INCREF` here.
How about using an object which is not singleton, instead of `(,)`?

**Comment by Alexander-N** [comment]
I don't follow, using separate objects instead of a singleton was my approach here. I don't like the `INCREF` either, could you explain your alternative a bit?

**Comment by konstin** [comment]
Thank you for the pull request! Those flaky tests have been a long-lingering problem and it's good to finally have them fixed.

---

The `get_object()` function should return either the pointer or the PyObject, since the are identical (incidentally they are even identical in memory). I'd return only the PyObject and use `.as_ptr()` where you need the pointer.

The incref usage is fine, even though after a quick glance it looks like it is only actually required in one place. However you always need to call decref in the end, otherwise your leaking memory. Those `cnt` variables also shouldn't be required any more since we can just compare with 1 and 2. Having constants will also make sure we're not accidentally using a singleton again.

**Comment by konstin** [comment]
That clone_ref solution is much better that INCREF'ing :+1:

**Pull request merged**
