### PR TITLE
Remove default from ReturnTypeIntoPyResult

### PR DESCRIPTION
**Pull request by kngwyu**
It passes tests, but I haven't tested its backward compatibility yet :thinking:

### CODE REVIEW

**Comment by konstin** [comment]
That's interesting, at least the last one was required when I last checked.

**Comment by kngwyu** [comment]
Really?
Then I need to try other compiler version :thinking:

**Comment by kngwyu** [comment]
I tried to add same changes to 13d4d66f(2 weeks ago) and compile it with rustc 1.32.0-nightly (25a42b2ce 2018-11-07).
It passed tests.

**Comment by kngwyu** [comment]
Hoops, now I noticed this PR breaks rust-numpy's [impl FromPyObject for PyArray](https://github.com/rust-numpy/rust-numpy/blob/master/src/array.rs#L118)... and no idea to avoid confliction, because we can't override `PyTryFrom`!

**Comment by kngwyu** [comment]
@konstin 
Why we have 2 conversion traits, `FromPyObject` and `PyTryFrom`?

**Comment by konstin** [comment]
Not really sure tbh, but apparently `FromPyObject` is implemented through `PyTryFrom` with some impls for native rust types added.

**Pull request merged**
