### PR TITLE
Add __pyo3__ attribute to native modules

### LINKED ISSUE #3426: Add '__pyo3_version__` to native modules compiled with PyO3
From https://github.com/sphinx-doc/sphinx/issues/11662#issuecomment-1702462095

> To be cheeky, could I ask if there is there a 'blessed' way to introspect if a module is PyO3 generated? It seems the variables mod.build_profile and mod.build_info might be heuristics, but a __PYO3__ = True flag or similar (a la '__pypy__' in sys.modules) might be useful for future cases?

I can't think of one which exists right now, it seems like a practical improvement to have `__pyo3_version__` as a standard attribute in compiled PyO3 modules?

### PR DESCRIPTION
**Pull request by ongchi**
Closes #3426

### CODE REVIEW

**Comment by mejrs** [comment]
Thanks!

What is your motivation for using a (handwritten?) pyclass for this? We've so far avoided this because pyo3 is linked statically; when two users write their own pyo3 modules, they'll have two different `PyO3Attr` types. (See the discussion around `PanicException` for why this can be problematic).

**Comment by adamreichold** [comment]
> We've so far avoided this because pyo3 is linked statically; when two users write their own pyo3 modules, they'll have two different PyO3Attr types. (See the discussion around PanicException for why this can be problematic).

I think the consensus reached so far is that we should ship a separate (pure Python for now) package called something like `pyo3_runtime` on PyPI which would contain shared types like `PanicException` and `PyO3Attr`, c.f. the discussion in the (eventually rejected) approach proposed in #3073 .

**Comment by davidhewitt** [comment]
Agreed, I've been meaning to do that for aaaaages, and finally did it! 😂 

#3450 
https://pypi.org/project/pyo3-runtime

**Comment by ongchi** [comment]
> What is your motivation for using a (handwritten?) pyclass for this?

All because I'm noob.🤡

BTW, I think it will be nice if pyo3 modules include some build information (e.g. rust version, build target, features...) automatically with a general interface to fetch this info. This shall benefit both developers and users who install packages from pypi, could providing useful context for debugging/issue tracking.

**Comment by adamreichold** [comment]
> BTW, I think it will be nice if pyo3 modules include some build information (e.g. rust version, build target, features...) automatically with a general interface to fetch this info. This shall benefit both developers and users who install packages from pypi, could providing useful context for debugging/issue tracking.

I think https://github.com/PyO3/pyo3-built might be what you are looking for?

**Comment by ongchi** [comment]
Cool! I'm not aware of that. Thanks for pointing this out.

**Pull request closed without merging**
