### PR TITLE
Selecting the whole workspace conflicts with package selection in llvm_cov_command.

### PR DESCRIPTION
**Pull request by adamreichold**

### CODE REVIEW

**Comment by adamreichold** [comment]
Ok, different even weirder error on Windows...

**Comment by davidhewitt** [comment]
https://github.com/rust-itertools/itertools/issues/645 - I see you figured this too

**Comment by adamreichold** [comment]
> [rust-itertools/itertools#645](https://github.com/rust-itertools/itertools/issues/645) - I see you figured this too

I was waiting for a successful pipeline using 0.10.3 as proof of the regression before submitting the upstream bug report. :-)

**Review by davidhewitt — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
