### PR TITLE
use `datetime.fold` to distinguish ambiguous datetimes when converting

### LINKED ISSUE #4722: `DateTime<Tz>`'s implementation for `FromPyObject` does not consider Pythons's `datetime.fold` attribute
When extracting an ambiguous time from `DateTime<Tz>`, PyO3 will raise a ValueError. Snippet from `chrono.rs`:

```rust
let naive_dt = NaiveDateTime::new(py_date_to_naive_date(dt)?, py_time_to_naive_time(dt)?);
naive_dt.and_local_timezone(tz).single().ok_or_else(|| {
    PyValueError::new_err(format!(
        "The datetime {:?} contains an incompatible or ambiguous timezone",
        dt
     ))
})
```

So if your Python datetime is `datetime(2024, 11, 3, 1, 30, 0, tzinfo=ZoneInfo("America/Chicago"), fold=1)`, PyO3 will raise the ValueError.

However, in [PEP 495](https://peps.python.org/pep-0495/) (added in Python 3.6), all `time` and `datetime` objects contain a `fold` attribute to disambiguate ambiguous times. So the above example should not be ambiguous.

We should be able to easily handle this by using chrono's `LocalResult.Ambiguous` enum.

### PR DESCRIPTION
**Pull request by bschoenmaeckers**
fixes #4722

### CODE REVIEW

**Comment by bschoenmaeckers** [comment]
We should probably do this for the IntoPyObject case as well.

**Comment by bschoenmaeckers** [comment]
> > We should probably do this for the IntoPyObject case as well. Current implementation will always set fold to 0.
> 
> 
> 
> Thanks! Agreed. Implementation looks good to me. Perhaps we can add a round-trip test converting (non)ambiguous `DateTime<Tz>` into Python, then extracting them back and make sure they are the same? What do you think?

Current test verifies this behaviour as well

**Review by Icxolu — APPROVED** [review]
> Current test verifies this behaviour as well

Oops, I must have overlooked that part.

**Comment by bschoenmaeckers** [comment]
Great! Thanks for looking at my changes!

**Pull request merged**
