### PR TITLE
Start documenting abi3 support

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Review by davidhewitt — CHANGES_REQUESTED** [review]
This PR documents the `abi3` feature, but I understood we decided to invert the pattern and instead have an `unstable-abi` feature which would be enabled by default?

There was a commit on the `abi3` branch to this effect: https://github.com/PyO3/pyo3/pull/1152/commits/1941f4daefa940d5f5426061ba8598e781186031

However that change doesn't appear to be present in the latest version of #1152 - perhaps came unstuck with a merge conflict?

**Comment by kngwyu** [comment]
> I understood we decided to invert the pattern and instead have an unstable-abi feature which would be enabled by default?

I inverted the change to introduce `py3*-abi3` features.

**Comment by davidhewitt** [comment]
> I inverted the change to introduce py3*-abi3 features.

Can you elaborate? I don't think I can see these py3*-abi3 features on that branch at the moment either.

**Comment by kngwyu** [comment]
Sorry, I meant that 'I changed it to `abi3` so that it would be integrated well with `py3*-abi3` features that we're going to introduce based on the discussion in #1195'

**Comment by alex** [comment]
Yes, this documents the branch as it exists today, and I followed this documentation when I wrote the tests for setuptools-rust, so I'm sure it works :-)

**Review by davidhewitt — APPROVED** [review]
:+1: in that case I propose let's merge it and review everything on the abi3 branch!

**Pull request merged**
