### PR TITLE
Update spin

### PR DESCRIPTION
**Pull request by kngwyu**
To fix build in current nightly.
See https://github.com/mvdnes/spin-rs/pull/53 for detail.

### CODE REVIEW

**Comment by kngwyu** [comment]
Also removed unnecessary feature gates to fix doc tests.

**Comment by konstin** [comment]
Thanks!

In case anyone needs a release with the nightly fixes, I'll create one.

**Comment by kngwyu** [comment]
Thanks!
I'm planning to release rust-numpy so could you please make a release?

**Comment by konstin** [comment]
Done: https://github.com/PyO3/pyo3/releases/tag/v0.4.1

**Pull request merged**
