### PR TITLE
Handle null in PyIterator::from_object to fix #494

### LINKED ISSUE #494: SIGSEGV when PyIterator is given an integer
## 🐛 Bug Reports

`PyIterator` creates a `SIGSEGV` when passed an integer.

### 🌍 Environment

 - Your operating system and version: Arch Linux 5.1.4-arch1-1-ARCH
 - Your python version:  3.7.3
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: `pacman -S python`
 - Your rust version (`rustc --version`): `rustc 1.36.0-nightly (7158ed9cb 2019-05-15)`
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` yes, yes

### 💥 Reproducing

The following program will panic:

```rust
extern crate pyo3;

use pyo3::prelude::*;
use pyo3::types::PyIterator;

fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();

    let obj = 1.into_object(py);
    assert!(PyIterator::from_object(py, &obj).is_err());
}
```

with `Cargo.toml`:
```toml
[dependencies]
pyo3 = { git = "https://github.com/PyO3/pyo3" }
```

### PR DESCRIPTION
**Pull request by konstin**

### CODE REVIEW

**Comment by konstin** [comment]
I don't understand why the 3.5 tests for the pr build on travis keep failing. They pass for the other travis build and also pass locally.

**Comment by kngwyu** [comment]
image
Hmm :thinking:

**Comment by kngwyu** [comment]
`if ffi::PyIter_Check(ptr) != 0` looks the cause.

**Comment by konstin** [comment]
cpython calls `PyIter_Check` internally, and that code hasn't changed for 9 years: https://github.com/python/cpython/blob/82494aa6d947c4a320c09c58fe0f100cdcf7af0b/Objects/abstract.c#L2578

**Comment by kngwyu** [comment]
#71

**Comment by kngwyu** [comment]
Sorry, then I have no idea

**Pull request closed without merging**
