### PR TITLE
clarify error message on missing path

### PR DESCRIPTION
**Pull request by H4vC**
fix for https://github.com/PyO3/pyo3/issues/4277

### CODE REVIEW

**Comment by H4vC** [comment]
This is a trivial change.

**Comment by davidhewitt** [comment]
Thanks for the PR! We actually have #4303 also improving this line, but that got stuck in review limbo. Would you be willing to help finish that one off instead please? You could pull those commits and add some extra ones on top.

The changes waiting on that PR were:
- how to test it - just write a unit test that attempts to read from a nonexistent file at the bottom of the same file
- some suggestions to actually include `PYO3_CROSS_LIB_DIR` in the error message

**Comment by mrexodia** [comment]
> Thanks for the PR! We actually have #4043 also improving this line, but that got stuck in review limbo. Would you be willing to help finish that one off instead please? You could pull those commits and add some extra ones on top.
> 
> The changes waiting on that PR were:
> 
> * how to test it - just write a unit test that attempts to read from a nonexistent file at the bottom of the same file
> * some suggestions to actually include `PYO3_CROSS_LIB_DIR` in the error message

This change as-is would have saved me a lot of time already. Considering it's a 1-line change wouldn't it be good to merge this as-is and then refactor later?

**Comment by davidhewitt** [comment]
I completely agree and am sorry that this wasn't fixed sooner. Nobody wants time wasted by bad error messages.

I found a moment to push to #4043 just now, so let's merge that one. Thank you both for reminding me that this error message matters. (You were not the first folks to hit this case.)

**Comment by mrexodia** [comment]
Awesome, thanks for the quick fix!

**Pull request closed without merging**
