### PR TITLE
Add missing #[allow(unsafe_code)] attributes

### LINKED ISSUE #4394: unsafe code warn causes: "implementation of an `unsafe` trait"
### Bug Description

When trying to update to pyo3 0.22 in https://github.com/astral-sh/uv/pull/5590, i get the errors `implementation of an unsafe trait` and `usage of an unsafe block`, even though i don't use any unsafe in my code.

pyo3 should place appropriate annotations on generated code 

### Steps to Reproduce

```toml
[package]
name = "pyo3-unsafe"
version = "0.1.0"
edition = "2021"

[lints.rust]
unsafe_code = "warn"

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module", "abi3-py37"] }
```

```rust
use std::hash::Hash;

use pyo3::pyclass;

#[derive(Eq, Ord, PartialEq, PartialOrd, Clone)]
#[pyclass(get_all)]
pub struct VersionSpecifier {
    pub(crate) operator: Operator,
    pub(crate) version: Version,
}

#[derive(Eq, Ord, PartialEq, PartialOrd, Debug, Hash, Clone, Copy)]
#[pyo3::pyclass(eq, eq_int)]
pub enum Operator {
    Equal,
}

#[derive(Clone, Eq, PartialEq, PartialOrd, Ord)]
#[pyclass]
pub struct Version;
```

`cargo check`:
```
warning: implementation of an `unsafe` trait
 --> src/lib.rs:8:26
  |
8 |     pub(crate) operator: Operator,
  |                          ^^^^^^^^
  |
  = note: requested on the command line with `-W unsafe-code`

warning: usage of an `unsafe` block
 --> src/lib.rs:8:26
  |
8 |     pub(crate) operator: Operator,
  |                          ^^^^^^^^

warning: implementation of an `unsafe` trait
 --> src/lib.rs:9:25
  |
9 |     pub(crate) version: Version,
  |                         ^^^^^^^

warning: usage of an `unsafe` block
 --> src/lib.rs:9:25
  |
9 |     pub(crate) version: Version,
  |                         ^^^^^^^

warning: 4 warnings emitted
```

### Backtrace

_No response_

### Your operating system and version

Ubuntu 24.04

### Your Python version (`python --version`)

Python 3.12.3

### Your Rust version (`rustc --version`)

rustc 1.80.0 (051478957 2024-07-21)

### Your PyO3 version

0.22

### How did you install python? Did you use a virtualenv?

pyenv opt build

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by LilyFoote**
Fixes #4394.

### CODE REVIEW

**Comment by LilyFoote** [comment]
@davidhewitt Do we have a standard way to test this sort of thing? I also noticed we have some other `unsafe` usage without `#[allow(unsafe_code)]`. I'm happy to add those too if that's appropriate.

**Comment by davidhewitt** [comment]
Great question. From a quick try, it looks like adding `#![forbid(unsafe_code)]` to `src/tests/hygiene/mod.rs` will probably do the trick? We already try to cover all macros for hygiene there, so it's maybe a good way to cover them for unsafety at the same time :)

**Comment by Icxolu** [comment]
adding ui tests that should pass (for example i added `pymodule_missing_docs` a while ago) is also an option

**Review by davidhewitt — APPROVED** [review]
Looks good to me, thanks!

**Comment by EwoutH** [comment]
Thanks! When can we expect a new release which includes this bugfix (either 0.23 or a backport to 0.22.x)?

**Comment by davidhewitt** [comment]
I'm prepping 0.22.3 bugfix which includes this fix, to be released in the coming days.

**Comment by woodruffw** [comment]
Thank you for adding these attributes! FYI, they cause some changes to buildability for crates that disable `unsafe` at the top-level via `forbid(unsafe_code)`, since Rust apparently doesn't distinguish between macro expansions and first-party code for lint attributes.

The fix (in my case) was to weaken `forbid(...)` to `deny(unsafe_code)`, to allow the macro-expanded attributes to correctly override the top-level setting.

See https://github.com/woodruffw/pyrage/commit/68d66179f542c5ac21fae744311645663d877aae for an example of the above.

**Comment by mbuesch** [comment]
> I'm prepping 0.22.3 bugfix which includes this fix,

Note that this seems to have broken the build for users that declare `#[forbid(unsafe_code)]` in their main.rs.
IMO this should have been a semantic versioning major bump.

```
error[E0453]: allow(unsafe_code) incompatible with previous forbid
  --> my.rs:33:1
   |
33 | / create_exception!(
**snip**
   |
  ::: main.rs:11:11
   |
11 |   #![forbid(unsafe_code)]
   |             ----------- `forbid` level set here
   |
   = note: this error originates in the macro `$crate::pyobject_native_type_named` which comes from the expansion of the macro `create_exception` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0453]: allow(unsafe_code) incompatible with previous forbid

```

**Comment by LilyFoote** [comment]
Does `#[forbid(unsafe_code)]` trigger with `0.22.2`? If not, it feels really weird to me that us explicitly marking these uses of `unsafe` as allowed causes problems.

**Comment by mbuesch** [comment]
`forbid` means that the attribute cannot be `allow`ed subsequently.
`deny` means that the attribute can be `allow`ed subsequently.

Therefore, I changed my code to `#[deny(unsafe_code)]` and everything is fine.

It is Ok to have this kind of change in macros.
However, IMO it was an API change that required a major bump. I did not expect such a build breakage from a `cargo update` or a not-`--locked` build.

**Comment by davidhewitt** [comment]
Sorry that we broke builds here; that wasn't the intention, and I believed this to be a bugfix based on user reports that this lint was firing in their code.

Given that the lint wasn't firing for you despite the `forbid`, I can only assume we added this `allow` to places it's not needed, i.e. we added it to too many places.

Perhaps there is something we can do to adjust our testing methodology and get this partially reverted for 0.22.4.

**Comment by mbuesch** [comment]
Thanks for your helpful and quick answer.

Yes, it's a bit puzzling what's really going on. Maybe it depends on the Rust compiler version whether a lint triggers without this `allow` in the macros?
I use `Rust 1.81.0`.

Just to be sure I reverted my project back to `pyo3 0.22.2` with the original `#![forbid(unsafe_code)]` in place.
It shows no warning in the compiler and clippy runs.

**Comment by Icxolu** [comment]
I did a bit of investigation with this reverted and the reproduction from #4394. The lint seems to trigger only on the
`#[pyclass(get_all)]` option and goes away if that is removed. The additional code for `get_all` is here
https://github.com/PyO3/pyo3/blob/0079003c49c2b7ac1e5c66b3f73f2ef11621476f/pyo3-macros-backend/src/pymethod.rs#L769-L799

and in contrast to other emitted code with `unsafe` in it, this one has a `Span`. And if I remove that span, then the warning goes away with it. So maybe the correct solution is to make sure to only emit `unsafe` code without a `Span`?

But I'm not really sure why that works. Without an explicitly set `Span`, `quote!` uses the `call_site` span, which in my understanding should behave the same as if the generated code was written out manually, which is clearly not the case here...

**Comment by davidhewitt** [comment]
I've staged the revert onto #4575, so we will ship that when we get the other fixes done.

**Pull request merged**
