### PR TITLE
Fix being able to call arg-less `#[new]` with any args from Python

### LINKED ISSUE #2748: Generated __new__ method does not check args to enforce signature
### Bug Description

Firstly, thank you for creating this amazing crate!

I noticed today that when using `#[new]` to generate a `__new__` method with an empty signature, the generated code doesn't enforce that _args and _kwargs must be empty. As a result, it's possible to call the constructor from Python and provide unused arguments without raising an exception. This could be confusing, for example the developer might expect the kwargs to set field values. I think this is a bug.

Here's part of the code generated by the macros, from `cargo expand`:

```
    impl Foo {
        unsafe extern "C" fn __pymethod___new____(
            subtype: *mut _pyo3::ffi::PyTypeObject,
            _args: *mut _pyo3::ffi::PyObject,
            _kwargs: *mut _pyo3::ffi::PyObject,
        ) -> *mut _pyo3::ffi::PyObject {
            use _pyo3::{callback::IntoPyCallbackOutput, pyclass_init::PyObjectInit};
            let gil = _pyo3::GILPool::new();
            let _py = gil.python();
            _pyo3::callback::panic_result_into_callback_output(
                _py,
                ::std::panic::catch_unwind(move || -> _pyo3::PyResult<_> {
                    let result = Foo::new();
                    let initializer: _pyo3::PyClassInitializer<Foo> = result.convert(_py)?;
                    initializer.into_new_object(_py, subtype)
                }),
            )
        }
    }
```

### Steps to Reproduce

```
#![allow(unused_variables)]
use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

#[pyclass]
struct Foo {}

#[pymethods]
impl Foo {
    #[new]
    pub fn new() -> Self {
        Foo {}
    }
}

pub fn main() -> PyResult<()> {
    pyo3::prepare_freethreaded_python();
    Python::with_gil(|py| {
    	let locals = [("Foo", py.get_type::<Foo>())].into_py_dict(py);
    	py.run("print(Foo()); print(Foo(123)); print(Foo(bar=123))", Some(locals), None)
    })
}
```

This code prints three objects, without raising any exceptions. The expected behavior would be to print the first and raise an exception on the second (and third of course).

### Backtrace

_No response_

### Your operating system and version

WSL2

### Your Python version (`python --version`)

3.11.0

### Your Rust version (`rustc --version`)

rustc 1.60.0-nightly (22e491ac7 2022-01-13)

### Your PyO3 version

0.17.3

### How did you install python? Did you use a virtualenv?

venv

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by birkenfeld**
Fixes #2748

Note that the removed check only triggered for `#[new]` anyway, since other arg-less pymethods use the `NOARGS` argument convention which is not available for `tp_new`.

There's some confusion going on with the `py` argument, I'll open an issue for that.

### CODE REVIEW

**Comment by birkenfeld** [comment]
Oh great, another MSRV bump (`rayon-core`) in a semver-compatible version bump. To the 2021 edition nonetheless.

**Review by davidhewitt — APPROVED** [review]
Ooof, thanks for fixing,!

**Comment by birkenfeld** [comment]
Hmm, that test failure is interesting. The base class' `__new__` is called implicitly, it seems, with the same arguments?

**Comment by birkenfeld** [comment]
Added a bit to the guide that explains the behavior.

**Review by davidhewitt — APPROVED** [review]
Thanks, this is definitely a correct fix and it's good to document existing behaviour.

I think there's potential for improvement around how to control invocation of `__new__` and `__init__` with inheritance, however I don't have a good answer for that right now and it's definitely for a future discussion anyway.

**Pull request merged**
