### PR TITLE
Replacing PyObject with Py<'p, PyObject>

### PR DESCRIPTION
**Pull request by fafhrd91**

### CODE REVIEW

**Comment by fafhrd91** [comment]
@messense I disabled set, I don't have time to fix code right now, will fix later

**Comment by messense** [comment]
@fafhrd91 Sure, I'll try this branch and help fix tests if I can to help myself wrap my head around it.

**Comment by fafhrd91** [comment]
idea is very simple. I introduced two smart pointers, each of them represents state of  `ffi::PyObject` pointer.

`PyPtr` - it just a safer version of `ffi::PyObject` pointer (parked pointer). you can not do anything with it, but it has `Send+Sync` bounds. and you can unpark it into `Py` pointer.

`Py<'p, T>` on other hand pointer with `GIL` lifetime, so it can not exist outside of `GIL` context. (unparked pointer). and lifetime `<'p>` represent `GIL`, so it is safe to access python api and custom rust class. 

here is how access to custom class work. we store rust struct in `ffi::PyObject` instance, so all we need to know is `offset` to the struct. and `offset` just extra python info like ref counters, various debugging info, etc or if we introduce proper python inheritance, then it would contain data for parent classes.

if we know offset, then it just unsafe pointer math https://github.com/PyO3/PyO3/blob/pyptr/src/pyptr.rs#L265
interesting part is, if we know that instance reference is from `Py<>` pinter we can calculate location of `ffi::PyObject` pointer, just `current mem address - offset`, all we need is to have guarantee that current reference is actually from `Py<>` pointer, but I am not sure if we can get this guarantee statically.

**Comment by fafhrd91** [comment]
ok, I played more with protocol implementation. it is not possible to use it with `Py<'p, T>` pointer.
I guess we'll need modify code during macro expansion.

**Comment by fafhrd91** [comment]
ok, seems branch more or less stable. some ergonomics work is required, but I think base idea is settled

**Pull request merged**
