### PR TITLE
Remove PyToken

### PR DESCRIPTION
**Pull request by konstin**

### CODE REVIEW

**Comment by kngwyu** [comment]
Wait...
The main usage of `PyToken` is to retrieve `Python` in extension, like https://github.com/kngwyu/rogue-gym/blob/master/python/src/lib.rs#L269.
So my question is: how can we retrieve `Python` in extension?
By `Python::assume_gil_acquired`?

**Comment by konstin** [comment]
The examples use the following:

```
let gil = GILGuard::acquire();
let py =  gil.python();
```

I'd like to unify those to lines, but that's a bit difficult (#213). You can also have `py: Python` injected as parameter for custom functions and methods.

**Comment by konstin** [comment]
(I hope both ways are documented, if not, we should definitely add them)

**Comment by fafhrd91** [comment]
Just a note GILGuard is actual lock, while pytocken was just type facade

**Comment by kngwyu** [comment]
But since `pymethod` and `pyclass` can't have lifetime, I think both ways are still more restrictive than `PyToken`.
For example, we can't compile this snippet by lifetime mismatching.
```rust
struct A {.. }
#[pymethods]
impl A {
...
    fn new_array(&self, py: Python) -> PyResult<&PyArray3<f32>> {
        Ok(PyArray3::new(py, [1, 2, 3], false))
    }
}
```

So honestly I don't think it's a ergonomics improvement, unless `pyclass` and `pymethods` become able to have lifetime parameters.

**Comment by konstin** [comment]
The main reason I've removed PyToken was because it was unsound while not been required in most case (except ones like your example). It would be definitely interesting to see if we can support pyclasses with a 'p for Python<'p> lifetime. It's not the best solution, but if you know that you're classes make the same guarantees as the native classes in pyo3 itself, i.e. you can only get a &'p instance, than you can (internally unsafe) impl PyObjectWithGIL.

**Pull request merged**
