### PR TITLE
Add Blog post in Articles and other media section 

### PR DESCRIPTION
**Pull request by AdilZouitine**
Hi there 👋,

This pull request adds a link to a blog post in the PyO3 README under the "Articles and other media" section. The blog post, titled "How we extended the River stats module with Rust using PyO3," details our experience in utilizing PyO3 to improve the performance of the River library's stats module.

### CODE REVIEW

**Review by messense — APPROVED** [review]
Nice post, thanks!

bors r+

**Comment by messense** [comment]
[GitHub Packages is having issues](https://www.githubstatus.com/incidents/ybnn77s3lyf8), let's try land this later.

**Comment by messense** [comment]
bors retry

**Comment by kngwyu** [comment]
It's cool, thanks. I really like your visualization on how the extension looks like from Python:
https://boring-guy.sh/img/river-rust/visual_rust_stats.png

**Comment by AdilZouitine** [comment]
> It's cool, thanks. I really like your visualization on how the extension looks like from Python: https://boring-guy.sh/img/river-rust/visual_rust_stats.png

Thank you! 🤗

**Pull request merged**
