### PR TITLE
release: 0.16.4

### PR DESCRIPTION
**Pull request by adamreichold**
I added a changelog entry for the coverage change because https://github.com/PyO3/rust-numpy/pull/316 revealed that this also affects downstream crates depending on PyO3.

@davidhewitt Hopefully, this reduces the busy work for you a bit.

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks, it would be cool to add #2263 to this too

**Comment by adamreichold** [comment]
> Thanks, it would be cool to add #2263 to this too

Yes, I think that would make sense. Will rebase when that PR is merged.

**Comment by adamreichold** [comment]
@davidhewitt Keeping with the theme of reducing busy work, I tried drafting a GitHub release for you to review before publishing. Is there a command or script you use to generate the contributors list?

**Comment by davidhewitt** [comment]
Thanks!

No script; I just use the GitHub UI https://github.com/pyo3/pyo3/compare/v0.16.3...HEAD

Every time I do it I think I should write a script and then never find the time 😂

**Comment by adamreichold** [comment]
> Every time I do it I think I should write a script and then never find the time joy

https://gist.github.com/adamreichold/b62493c129a55c0929b742990acb4185 appears to work. If it turns out to be helpful, maybe it can get a more permanent place of residence (and some amenities like error checking).

**Comment by davidhewitt** [comment]
Nice! Yes I think it's fine to commit it somewhere to the repo.

**Comment by adamreichold** [comment]
Rebased and updated the draft release.

**Comment by davidhewitt** [comment]
Thanks! I didn't push this yesterday in the end because I wanted to wait until after 0.15.2 published. I couldn't remember if I pushed this and _then_ 0.15.2 whether crates.io would list 0.16.4 or 0.15.2 as the latest version.

**Comment by davidhewitt** [comment]
Force-pushed to update the date.

**Comment by davidhewitt** [comment]
Rebased a final time to pick up #2293

**Comment by davidhewitt** [comment]
Release is live. Thanks again @adamreichold for all the work writing fixes, reviewing, and preparing this release 👍

**Comment by adamreichold** [comment]
I fear we might have regressed w.r.t. finding the Python interpreter: https://github.com/PyO3/rust-numpy/runs/6029114285?check_suite_focus=true

**Comment by adamreichold** [comment]
It might also be Maturin, because the part where

```
  🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
```

seems wrong as the crate does not use the stable ABI.

**Pull request merged**
