### PR TITLE
refs #4300, adds a `sealedclass` attribute that allows opting into the usage of unit enum variants with complex enums.

### PR DESCRIPTION
**Pull request by Molkars**
https://github.com/PyO3/pyo3/issues/4300

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks for the PR! Overall I am ok for having an opt-in for this use-case, as it helps to mitigate the concern I had about refactoring causing subtle behavioural changes.

That said, I would like to discuss a few possible adjustments:
- What behaviour do you want the unit enums to have? Do you want them to be C-like constants, or empty-tuple-like? It looks like you have opted for empty-tuple-like here. Do you ever want to mix both kinds in a single enum?
- I'm not convinced by the `sealedclass` name, it's not intuitive to me how that connects to the unit variants. How about something like `#[pyclass(unit_variants = "c-like")]` or `#[pyclass(unit_variants = "tuple-like")], which is more direct and could even give the user the choice of behaviour.
- Similarly, would it be better if this was a `#[pyo3(c_like_unit_variant)]` attribute on each unit variant, instead of once on the class? That would allow mixing and matching, and changing `UnitVariant` into `#[pyo3(tuple_like_unit_variant)]` might still be better than the current suggestion to change it to `UnitVariant {}`.

**Comment by Molkars** [comment]
I implemented the new annotations. I marked this PR as a draft since I have to do some more work on it tomorrow.

I have to figure out what to do for the static symbols in python-land. I also need to revise what's going on with the `__new__` function for the unit variants (right now it's disabled for unit variants.) I would like to make the constructor return a lazy-singleton object, instead of creating a new instance, but I would like to know if you think that's a good idea before I do it. As far as I know, there is no way in python to disable a classes constructor and also create a singleton of it without a superclass.

**Comment by Molkars** [comment]
@davidhewitt could I get your feedback on the above?

**Comment by davidhewitt** [comment]
Sorry for the long gap here (I was quite busy with parternity leave and then catching up with other PRs etc)

Overall I'm really happy with the design here and would be fine to see this resurrected and merged.

> I would like to make the constructor return a lazy-singleton object, instead of creating a new instance, but I would like to know if you think that's a good idea before I do it. 

I think that's the correct idea (so that e.g. identity comparisons with `is` work as users might expect). I think we managed to do this already for c-like enums so you might be able to re-use some existing machinery there. It's a little while since I looked at that code so it's not fresh in my memory what we did.

**Comment by Molkars** [comment]
We decided to go a different path so I didn't have time to spend on it. I think I may be revisiting this necessity in the future but it likely wouldn't be for at least 4 months

**Pull request closed without merging**
