### PR TITLE
Guard against PyUnicode_AsUTF8AndSize returning null in PyString::as_bytes

### PR DESCRIPTION
**Pull request by goffrie**
Noticed that this is only a debug_assert when this case is actually possible.

### CODE REVIEW

**Comment by kngwyu** [comment]
https://github.com/python/cpython/blob/3.7/Objects/unicodeobject.c#L3825

So you mean `PyUnicode_UTF8(unicode)` can be NULL?
Hmm...

**Comment by ijl** [comment]
Python unicode can contain surrogates such as "\ud800" that will cause a null pointer to be returned here. as_bytes() could return a PyResult.

**Comment by kngwyu** [comment]
@ijl 
Thanks for your advice.
So @goffrie could you please change `as_bytes` to return `PyResult`?
The error case is very rare but still it can happen.

**Comment by Alexander-N** [comment]
@ijl Could you provide an example how surrogates would cause problems here? I can't come up with a test case and fail to see why `PyUnicode_AsUTF8AndSize` would return NULL in this case. Maybe I'm misunderstanding the issue, but for example this works:
```rust
#[test]
fn test_as_bytes_surrogate() {
    let gil = Python::acquire_gil();
    let py = gil.python();
    let s = "���";
    let obj: PyObject = PyString::new(py, s).into();
    let py_string = <PyString as PyTryFrom>::try_from(obj.as_ref(py)).unwrap();
    assert_eq!(s.as_bytes(), py_string.as_bytes());
}
```

**Comment by ijl** [comment]
@Alexander-N � is UTF-8 still, but `\ud800`, which is a UTF-16 surrogate, causes `PyUnicode_AsUTF8AndSize` to return null.

**Comment by Alexander-N** [comment]
I got it now, thank you! Strange that these can be valid Python strings...

**Comment by kngwyu** [comment]
Closed in favor of #639

**Pull request closed without merging**
