### PR TITLE
Fix Changelog typos and reorder entries

### PR DESCRIPTION
**Pull request by davidhewitt**
I made the following changes for the "Unreleased" changelog entries:
- Fixed a typo "reutrn" -> "return"
- Added full-stops to all changelog entries for consistency
- Added PR numbers to all entries
- Reordered the entries so that lower PR numbers come first

### CODE REVIEW

**Comment by davidhewitt** [comment]
CI failure is because of #747

**Comment by kngwyu** [comment]
Sorry looks I can't touch 'Restart build' button on travis and maybe need rebasing :sweat:

**Comment by davidhewitt** [comment]
Rebased now CI should be green.

**Comment by kngwyu** [comment]
Thank you!

**Pull request merged**
