### PR TITLE
Update constants for py3.12, which fixes struct sizes

### PR DESCRIPTION
**Pull request by alex**
See 766d2518ae8384c6bd7f82727defeb86847ccf64

### CODE REVIEW

**Comment by alex** [comment]
I think it'd be appropriate to add the labels for no changelog, and to run the full CI since this impacts 3.12.

**Comment by adamreichold** [comment]
@alex I think you need to push again (e.g. just amending the commit) to trigger a new pipeline with the full build.

@davidhewitt Shouldn't the FFI check flagged this?

**Comment by alex** [comment]
Alright, looks like we're good here.

**Review by adamreichold — APPROVED** [review]
Would still be nice to remove the second commit before merging.

**Comment by alex** [comment]
Ah sure, Ill rebase it out.

**Comment by alex** [comment]
Done

**Pull request merged**
