### PR TITLE
Mention `send_wrapper` in the migration guide

### PR DESCRIPTION
**Pull request by davidhewitt**
Based on @konstin's comment in Gitter.

### CODE REVIEW

**Comment by davidhewitt** [comment]
(Sorry for the force-pushes; I tweaked the wording and commit message shortly after opening the PR.)

**Comment by kngwyu** [comment]
Hmm... :thinking: 
`SendWrapper` is internally a pair of `Box<T>` and `ThreadId`.
I don't want to recommend it as a thread-safe alternative of `T` since it requires redundant `Box`.

**Comment by davidhewitt** [comment]
Ok :+1:

**Comment by konstin** [comment]
While it gives a small performance hit, it is imho still preferable to `unsafe impl Send` which can cause nasty bugs if used incorrectly.

**Comment by birkenfeld** [comment]
This change showed both possibilities, so it's definitely helpful when the contents are *not* threadsafe after all.

**Comment by davidhewitt** [comment]
I would also be in favour of encouraging users to use `send_wrapper` instead of unsafe impl if they don't know what they're doing.

As a few of us are in favour of this, reopening.

**Comment by kngwyu** [comment]
I agree that we provide no good interface for a class that we don't want to send.
So, as a *builtin* alternative of send-wrapper, I opened #1009.

**Comment by kngwyu** [comment]
Closed in favor of #1009

**Pull request closed without merging**
