### PR TITLE
Add FFI definition for PyObject_AsFileDescriptor

### LINKED ISSUE #935: Add PyObject_AsFileDescriptor to fileobject FFI declarations
Right now the PyO3 FFI API does not allow us to take file objects and convert them to file descriptors.
We should add that function so we can implement #933.

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #935.

### CODE REVIEW

**Comment by davidhewitt** [comment]
FYI as per Gitter chat I'll review this later

**Comment by thedrow** [comment]
Done :)

**Comment by davidhewitt** [comment]
Thanks - I fixed a typo (missed a closing bracket off the end, was my fault from typing my last comment on my phone yesterday 😄)

**Comment by davidhewitt** [comment]
Thank you!

**Pull request merged**
