### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by konstin**
@kngwyu Do have the permissions to publish a release on crates.io?

CC @rth since you asked on gitter

### CODE REVIEW

**Comment by kngwyu** [comment]
@konstin 
As I said before, I don' have it since I'm not a member of the PyO3 github group.

**Comment by konstin** [comment]
@fafhrd91 Could you please add @kngwyu to the github org and the team that has permission to publish to crates.io?

**Comment by fafhrd91** [comment]
@konstin i changed your permission, i think you should be able to add people and give permissions

**Comment by kngwyu** [comment]
I think #472 #476 #477 #488 are should be merged before the release.

**Comment by konstin** [comment]
@fafhrd91 Thank you!

@kngwyu I've invited you to the team.

I've merged #476, #477 and #478. Go ahead with #472 as you wish.

**Pull request merged**
