### PR TITLE
Add PyAnyMethods.try_iter and deprecate .iter

### LINKED ISSUE #4550: `PyAnyMethods::iter()` is a footgun, should be called `try_iter()`
### Bug Description

`PyAnyMethods::iter()` returns a `PyResult<&Bound<PyIterator>>`. And `Result` is an iterator. So it's very easy to accidentally iterate over it directly.

### Steps to Reproduce

Consider the two seemingly identical functions:

```rust
fn iterate(s: Vec<&PyResult<Bound<PyAny>>>) {
    for obj in s.iter() {
        do_something(obj);
    }
}

fn iterate2(s: Bound<PySequence>) {
    for obj in s.iter() {
        do_something(obj);
    }
}
```

They seem identical, but `iterate2()` will iterate over the `PyResult` returned from `PyAnyMethods::iter()`, so it will always have a single item, the original sequence!

And yes, I just discovered this the hard way.

### Your PyO3 version

0.22

### Additional Info

I would suggest:

1. Deprecating `iter()`.
2. Creating a new, identical function and calling it `try_iter()`. The new name will suggest that it returns a `Result<>` and therefore requires a `?` or equivalent handler.

### PR DESCRIPTION
**Pull request by LilyFoote**
Fixes #4550.

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks, sounds like `try_iter` is the preferred choice. While we're here, perhaps let's add some detail to the documentation to make it more clear that you need to handle the result before trying to iterate? (An example might be nice.)

**Comment by LilyFoote** [comment]
I've added an example, but I'm open to a better one.

**Comment by mejrs** [comment]
> I've added an example, but I'm open to a better one.

I nominate:
```rust
fn does_it_have_the_answer(obj: &Bound<'_, PyAny>) -> bool {
    if obj.extract() == Some(42_u8) {
        true
    } else if obj.extract() == Some("42") {
        true
    } else if let Ok(iter) = obj.try_iter() {
        for item in iter() {
            if let Ok(item) = item {
                if does_it_have_the_answer(item) {
                    return true;
                }
            }
        }
    }
    false
}
```
(maybe add some comments to explain what we're doing)

**Comment by Icxolu** [comment]
For my taste that does have a bit too much complexity that is not really relevant for the fallibility of the iterator. I would prefer something a bit simpler, but I don't have a good suggestion in mind right now... At least I think the `try_iter` call should be at the start of the example and introducing recursion does not feel particularly necessary.

**Review by davidhewitt — APPROVED** [review]
I think as we're a bit stuck of ideas for the perfect example, let's just proceed to merge. I'd prefer see this get into 0.23 with a slightly subpar example and refine another time. Thanks all!

**Pull request merged**
