### PR TITLE
Add nightly-optimizations feature

### PR DESCRIPTION
**Pull request by davidhewitt**
Add a feature to gate the sequence implementations using buffer + specialization behind feature flag.

Questions: 
 - Should this feature be disabled or enabled by default?
 - How should we configure CI to test this feature?

TODO:
- [ ] I'd like to write some documentation about this feature before merge. Wanted to propose this feature before I spend too long writing docs.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thank you, but I don't think we should do this now since we can't test that we can compile the code without `#![feature(specialization)]`.

**Comment by davidhewitt** [comment]
That's ok. I'm happy to leave this PR to wait until we have finished removing specialization from `PyClass`.

Also I have some other ideas I am exploring with `ManagedPyRef` / `ToBorrowedObject` to remove specialization there, which will be the only other stuff left

**Comment by davidhewitt** [comment]
FYI I continued to look at `ManagedPyRef` and `ToBorrowedObject`. I would propose that we remove `ManagedPyRef` for now (see #930) and add `nightly-optimizations` feature to `ToBorrowedObject`'s specialization.

I will leave this here for now until the provider pattern to remove specialization from `PyClass` is implemented. After that, we should be able to test this PR fully - and compile without specialization!

**Comment by davidhewitt** [comment]
Just for completeness - my vision is that once we have made this feature gate, we can rework these optimizations to use `min_specialization`. And then we should eventually be able to get them onto stable Rust and remove the feature flag.

The feature flag will be a bridge which lets us compile on stable before `min_specialization` is stabilized.

**Comment by davidhewitt** [comment]
FYI I will rebase this after #961 is merged - and (fingers crossed) add a CI for stable rust at the same time.

**Comment by davidhewitt** [comment]
I will rebase this tonight unless you want me to close this and we focus on #969 ?

**Comment by kngwyu** [comment]
I'm sorry I close this PR in favor of #961

**Pull request closed without merging**
