### PR TITLE
release: 0.14.3

### PR DESCRIPTION
**Pull request by davidhewitt**
Since there have been a few FFI fixes, in particular #1791 which causes a nasty crash, I felt it would be worth cherry-picking these on top of 0.14.2 and creating a 0.14.3 release.

As these commits all exist in `main` I don't think it's worth actually merging this branch, I'll create a separate PR to update the CHANGELOG to separate out the contents released in 0.14.3 when this goes live. Perhaps there's a lesson for the future to consider having an 0.14.x branch, 0.15.x branch etc., although that in itself also creates extra work.

I propose I'll put this live next weekend, I was thinking it could be nice to also cherry-pick #1794 (and maybe non-breaking parts of #1793) into this release, so that PyOxidizer is able to move ahead with its PyO3 port without waiting for us to release 0.15 (which might be a couple months off).

cc @indygreg

### CODE REVIEW

**Comment by Eric-Arellano** [comment]
It's worked well for us with Pants to create a release branch as soon as rc0 goes out for a particular release. It allows us to immediately land breaking changes to `main` without a cooling off period, and keeps us disciplined with cherry picking bug fixes / non-breaking improvements.

**Comment by davidhewitt** [comment]
Thanks, that's definitely interesting food for thought. 

I also realised this morning that in our CHANGELOG we use git ranges to produce comparison links between each PyO3 version. It might get more fiddly to create those if we have a slightly nonlinear history. But maybe that's fine.

**Comment by davidhewitt** [comment]
CI seems to be borked so I'm going to close and open the PR... ?

**Comment by davidhewitt** [comment]
Hmm still no CI. Very confusing.

**Comment by messense** [comment]
> Hmm still no CI. Very confusing.

Because of the conflicting file? See https://github.community/t/run-actions-on-pull-requests-with-merge-conflicts/17104

**Comment by davidhewitt** [comment]
Ah interesting, somehow I'd never been aware of that.

I think I'll have to make a 0.14 release branch in that case, and change this PR to merge into that.

**Comment by davidhewitt** [comment]
Aha looks like that's working now.

**Comment by tiran** [comment]
Could you please cherry-pick https://github.com/PyO3/pyo3/pull/1812 into 0.14.3, too? Thanks!

**Comment by mejrs** [comment]
And also both of the decref ones? https://github.com/PyO3/pyo3/pull/1810 and https://github.com/PyO3/pyo3/pull/1806

**Comment by davidhewitt** [comment]
Thanks, cherry-picked the new fixes. 

I'll put this live tonight unless I hear a reason to wait!

**Comment by davidhewitt** [comment]
Release is live!

**Pull request merged**
