### PR TITLE
netlify: generate all redirects automatically

### PR DESCRIPTION
**Pull request by davidhewitt**
Uses the versions from the pulled `gh-pages` tarball to generate the `docs.rs` redirects. Simplifies the release process.

### CODE REVIEW

**Review by messense — APPROVED** [review]
Nice!

**Comment by davidhewitt** [comment]
bors r=messense

**Comment by op8867555** [comment]
Sorry if this isn't the right place to report, I think there is an extra `>` character not removed (.netlify/build.sh:32), which make pyo3.rs always redirect to a 404 now.

**Comment by davidhewitt** [comment]
Ooof! Many thanks @op8867555 for reporting, much appreciated and definitely a suitable place to report 😁

**Comment by davidhewitt** [comment]
Will fix in #2874

**Pull request merged**
