### PR TITLE
docs: fix missing char conversion

### PR DESCRIPTION
**Pull request by suriya-ganesh**
Thank you for contributing to PyO3!

By submitting these contributions you agree for them to be dual-licensed under PyO3's [MIT OR Apache-2.0 license](https://github.com/PyO3/pyo3#license).

Please consider adding the following to your pull request:
 - an entry for this PR in newsfragments - see [https://pyo3.rs/main/contributing.html#documenting-changes]
   - or start the PR title with `docs:` if this is a docs-only change to skip the check
 - docs to all new functions and / or detail in the guide
 - tests for all new or changed functions

PyO3's CI pipeline will check your pull request. To run its tests
locally, you can run ```nox```. See ```nox --list-sessions```
for a list of supported actions.

### CODE REVIEW

**Review by davidhewitt — APPROVED** [review]
Thanks!

**Comment by suriya-ganesh** [comment]
Very curious that the pipeline is failing. the commands are running on my local

**Comment by davidhewitt** [comment]
Yes, seems like just some flakiness 😭

**Comment by davidhewitt** [comment]
Ugh, I've asked upstream at https://github.com/rust-lang/rustup/issues/3530

**Pull request merged**
