### PR TITLE
Do not store return values in locals so that holders benefit from lifetime extension for temporaries.

### LINKED ISSUE #3138: E0716 "temporary value dropped while borrowed" in `#[pyfunction]`
### Bug Description

:wave: Love PyO3! 

Upgrading from `0.16` to `0.18` I'm seeing the following compiler error:

```
error[E0716]: temporary value dropped while borrowed
    --> src/externs/interface.rs:1024:17
     |
1021 | #[pyfunction]
     | -------------
     | |           |
     | |           temporary value is freed at the end of this statement
     | borrow later used here
...
1024 |   py_scheduler: &'py PyScheduler,
     |                 ^ creates a temporary value which is freed while still in use
     |
     = note: consider using a `let` binding to create a longer lived value
```

The code in question looks like:

```rust
#[pyclass]
struct PyScheduler(Scheduler);

// ...

#[pyfunction]
fn scheduler_metrics<'py>(
  py: Python<'py>,
  py_scheduler: &'py PyScheduler,
  py_session: &'py PySession,
) -> HashMap<&'py str, i64> {
  py_scheduler
    .0
    .core
    .executor
    .enter(|| py.allow_threads(|| py_scheduler.0.metrics(&py_session.0)))
}
```

### Steps to Reproduce

(Try and compile the code)

### Backtrace

_No response_

### Your operating system and version

Ubuntu 20

### Your Python version (`python --version`)

3.8

### Your Rust version (`rustc --version`)

rustc 1.69.0 (84c898d65 2023-04-16)

### Your PyO3 version

0.18.3

### How did you install python? Did you use a virtualenv?

`apt` and no venv

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by adamreichold**
Closes #3138

### CODE REVIEW

**Review by davidhewitt — APPROVED** [review]
Thanks, as discussed on #3140, let's move ahead with this solution. I won't merge just in case you want to play with refactoring the `OkWrap` pattern into a function or struct as suggested on that thread. (I am also fine with leaving that for the future, the macro code will be simpler once we ditch the deprecated `#[args]` and also I have a refactoring or two in my mind which maybe I'll get to one day.)

**Comment by adamreichold** [comment]
> I am also fine with leaving that for the future

I'd like to limit ourselves to the fix for now as I am seeing an obvious simplification by trying to extract the ok wrapping ATM.

bors r=davidhewitt

**Comment by adamreichold** [comment]
bors retry

**Comment by adamreichold** [comment]
bors retry

**Pull request merged**
