### PR TITLE
docs: mention PyBuffer

### LINKED ISSUE #954: Guide entry for PyBuffer
I can't see `PyBuffer` mentioned anywhere in the guide...

At the very least, we might want to add it to the [argument types](https://pyo3.rs/master/conversions.html#argument-types) section of `conversions.md`? Or maybe on [`types.md`](https://pyo3.rs/master/types.html).

### PR DESCRIPTION
**Pull request by davidhewitt**
Uses PEP 688 `types.Buffer` to describe `PyBuffer<T>` in the conversion tables. Will leave as draft until PEP 688 is finalised.

Closes #954

### CODE REVIEW

**Comment by adamreichold** [comment]
> Will leave as draft until PEP 688 is finalised.

The [PEP](https://peps.python.org/pep-0688/) seems to be accepted, so can this just be "undrafted"?

**Comment by davidhewitt** [comment]
Good spot! I've rebased and updated this PR to mention `collections.abc.Buffer` as per the accepted form of the PEP.

Interestingly the PEP now also defines `__buffer__` and `__release_buffer__` methods. We may want to consider support for them eventually; I'll create a new ticket.

**Comment by adamreichold** [comment]
It never stops... I think we need to bin `wasm-bindgen` to version 0.2.84 for the MSRV builds to avoid pulling in `syn` 2.0.

**Comment by davidhewitt** [comment]
Thanks for fixing MSRV! How would you feel if I started a patch to bump MSRV to 1.56 as per #3113 ? Would mean we would be waiting until mid June to release 0.19 (i.e. around one month from now)

**Comment by adamreichold** [comment]
> Thanks for fixing MSRV! How would you feel if I started a patch to bump MSRV to 1.56 as per https://github.com/PyO3/pyo3/issues/3113 ? Would mean we would be waiting until mid June to release 0.19 (i.e. around one month from now)

Personally, I would feel better to release the functionality created so far as 0.19 with our current MSRV (because we know it is compatible) and then immediately after that go about bumping both Rust and Python version requirements.

I do loathe the MSRV picket line, but I also think it is important work for us maintainers to make our crates available in as many environments as reasonably possible.

**Comment by adamreichold** [comment]
(This of course purely psychological, but 0.20 would also look nicer than 0.19 as "break-stuff-that-used-to-work" release.)

**Comment by adamreichold** [comment]
@davidhewitt Penny for your thoughts on whether to bump MSRV before or after releasing 0.19?

**Comment by davidhewitt** [comment]
I think lets release 0.19 first as you suggest. I'll try to write up a list of what I was hoping to get into 0.19 later

**Pull request merged**
