### PR TITLE
Add introduction to guide

### PR DESCRIPTION
**Pull request by davidhewitt**
I've been thinking about doing this for a while... I just added a very basic introduction page and added a copy of the README to the guide, because some topics are covered only in the README (and it's nice not to need to duplicate them).

### CODE REVIEW

**Comment by kngwyu** [comment]
How about placing `README` in `index.md`?

**Comment by davidhewitt** [comment]
I did consider this but decided I slightly preferred keeping them separate... Happy to merge them if you prefer it?

**Comment by davidhewitt** [comment]
... I decided to merge it 👍

**Review by kngwyu — APPROVED** [review]
Thanks :+1:

**Pull request merged**
