### PR TITLE
Exclude PyPy CI for windows

### PR DESCRIPTION
**Pull request by kngwyu**
I don't know what to do but for now, push some changes *experimentally*.

### CODE REVIEW

**Comment by kngwyu** [comment]
It looks like `tox.interpreters.via_path.get_python_info("pypy3")` causes the problem, but I have no idea why this started to fail.

**Comment by kngwyu** [comment]
I finally gave up...

**Comment by davidhewitt** [comment]
Let's create an issue to fix? And then I'll try to have a look some time.

**Comment by kngwyu** [comment]
:+1:

**Pull request merged**
