### PR TITLE
Clean up CHANGELOG to match keep-a-changelog more closely

### PR DESCRIPTION
**Pull request by davidhewitt**
Cleaned up the CHANGELOG to be more consistent with https://keepachangelog.com

- Changed `*` to `-` for bullets
- Removed unnecessary newlines
- Added missing release dates
- Added missing links
- Changed order of sections to always be `Added` / `Changed` / `Removed` / `Fixed` (to match the order on keep-a-changelog).

### CODE REVIEW

**Comment by davidhewitt** [comment]
Will rebase quickly after merge of #911...

**Comment by kngwyu** [comment]
Hmm, travis goes wrong :thinking: 
Could please `push --force` again?

**Comment by davidhewitt** [comment]
👍 travis looks alive this time so fingers crossed

**Comment by kngwyu** [comment]
Thanks!

**Pull request merged**
